### ISSUE TITLE
String substitution is not part of the current build for the elements folder

### ISSUE THREAD

**Issue by WilliamRClark** [noflo/noflo-ui#1013]
It doesn't look like the current gruntfile substitution handles the elements folder.  (See attachment for what the current build looks like when run.)

**Comment by WilliamRClark** [comment]
![substitutions](https://user-images.githubusercontent.com/5107798/97762389-be23a100-1ade-11eb-8cfa-230296c4caea.png)

**Comment by bergie** [comment]
That's weird, it shouldn't be necessary to run this with the elements, as Vulcanization inlines them into the index.html file (where things get substituted)

**Comment by WilliamRClark** [comment]
> That's weird, it shouldn't be necessary to run this with the elements, as Vulcanization inlines them into the index.html file (where things get substituted)

That explains it.  Vulcanization was broken for me on Windows.  I put this together while I was waiting for an answer for the fix.  I rebased my branch and the substitutions in index.html work!  No changes needed.  Closing bug,  and PR!
