### ISSUE TITLE
Group creation / selection doesn't seem to work

### ISSUE THREAD

**Issue by WilliamRClark** [noflo/noflo-ui#1032]
I can see it is possible to create groups because they appear to be there in the ReactTodoExample.  However, it isn't clear at all how multi-select is supposed to work.  Does multiple selection actually work on Windows, or is this related to: https://github.com/noflo/noflo-ui/issues/28?

**Comment by bergie** [comment]
Doesn't appear to be only Windows. I'm assuming this is a regression in the latest the-graph release. Will have to be investigated.

**Comment by WilliamRClark** [comment]
I've gone back through releases of the-graph as far as version 10.3 without finding one that this appears to work with.  Can you confirm what key selection should be triggering this?  Is this ctrl-right click correct?  This appears to work with arrows, not elements.

**Comment by bergie** [comment]
Looks like it was in noflo-ui after all, see #1036
