### ISSUE TITLE
multiple npm install issues

### ISSUE THREAD

**Issue by j2l** [noflo/noflo-ui#1095]
Hello,
I tried the npm way.
react-dom@<16.0.0 is required, 
ok
I check which was the latest version below 16, it's 15.7.0
npm i react@15.7.0
ok, but
react-fluid-table@0.4.2 requires a peer of react@>=16.8.0

npm uninstall react-fluid-table is not working, it's needed later in the build

npm run build
ERROR in ./src/components/RuntimeEvents.jsx
Module not found: Error: Can't resolve 'react-fluid-table' in 'C:\Users\pm\Downloads\noflo-ui-master\src\components'
 @ ./src/components/RuntimeEvents.jsx 4:0-42 72:42-47
 @ ./elements/noflo-packets.js
 @ ./elements/noflo-ui.js

re-installed, despite not the right version, it installed
re-build, passed

BTW `found 14 vulnerabilities (8 low, 3 moderate, 3 high)`
can't be fixed

npm start

> noflo-ui@0.29.1 start C:\Users\pm\Downloads\noflo-ui-master
> http-server browser/ -p 9999 -s -c-1

(node:7556) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

To finally get an empty screen and an error in console:
![image](https://user-images.githubusercontent.com/65325/106872636-5a35e900-6688-11eb-9568-789d288ae87e.png)

<anonymous> index.es.js:1
    Webpack 6
        l
        698
        l
        t
        r
        <anonymous>

I can't test more things for now.
If someone has the right versions and steps to make it work, please let me know :)

**Comment by bergie** [comment]
Try installing the exact versions we use by running `npm ci` instead of `npm install`.

And make sure you have a recent Node.js version. We're using 12

**Comment by j2l** [comment]
Thank you, it's working now.

But it's heavy, 625MB. As ci installs from packages lock file, what could be safely removed?

**Comment by bergie** [comment]
The build and test dependencies are pretty big (including a chromium instance for e2e tests with puppeteer). If you want to slim it down, see what we’re doing in the Dockerfile
