### ISSUE TITLE
404 in flowhub.io, platform.js.map not loading

### ISSUE THREAD

**Issue by stt** [noflo/noflo-ui#185]
There's an extra semicolon in app.js:39 at least on flowhub.io
```
sourceMappingURL=platform.js.map;
```

It results in 404 and makes js debugging with chrome devtools difficult.
On cursory look couldn't place the offending code in noflo-ui sourcecode however.

**Comment by jonnor** [comment]
Unable to reproduce on current http://app.flowhub.io (version 0.10).
