### ISSUE TITLE
Default runtime for new graph should be that of main graph

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#203]
Create a new graph in a project. Default selected runtime for new graph is always "Browser". Should be that of the main project instead.

**Comment by bergie** [comment]
Also somewhat related: #405

**Comment by bergie** [comment]
This already works:

![screenshot 2018-03-29 at 12 40 29](https://user-images.githubusercontent.com/3346/38084770-6e415dd2-334e-11e8-90ab-e7b6ac5253d0.png)
