### ISSUE TITLE
Preview on separate device

### ISSUE THREAD

**Issue by bergie** [noflo/noflo-ui#24]
Currently the 'previews' of client-side NoFlo applications run in a card inside the NoFlo UI, sandboxed to a separate `iframe`. For some applications it would be very useful to be able to preview instead on separate device(s), especially mobile.

In that case the workflow could be the following:

* Open a graph, click a *preview on separate device* button in the preview card's toolbar
* The preview card contents are replaced with a unique URL and a QR Code
* Open the URL on another device (or just another browser tab/window), and you'll get the preview page
* Messaging between the remote preview and NoFlo UI could happen either via WebSockets using a server in between, or via WebRTC data channels

**Comment by jonnor** [comment]
This works since several months back for noflo-browser. In the runtime selector, chose 'Run on device' and you'll get a QR code and URL which you can open on another device - and connect your Flowhub device there.
