### ISSUE TITLE
Would like separate windows for building component and browsing diagram

### ISSUE THREAD

**Issue by jpaulm** [noflo/noflo-ui#249]
Right now, I have one canvas showing either the diagram or the component I am working on.  It would be great if the component could be brought up in a separate window so I don't have to keep clicking on the list at the left and reselecting the current work items.  Alternatively, sort the list by most recently used.

**Comment by jonnor** [comment]
A workaround which is available now is to use two browser tabs - where is basically kept at the project at hand. One can copy-paste the URL from one tab to another to open the same view.

Improvements in the area of 'keeping an overview' which working on a component is appreciated, but I'm closing the issue as no-one has shown interest in working on it for over a year.
