### ISSUE TITLE
Syntx error in component not giving enough info

### ISSUE THREAD

**Issue by jpaulm** [noflo/noflo-ui#253]
I keep getting a rectangle in the bottom right that says "Syntax error, Unexpected token, ILLEGAL" .  Not very helpful!  It doesn't say which component it applies to, nor which line in the code is the culprit.  Displaying the token in question would be nice too!
There may be something (in one of the components!) which is perfectly obvious to someone who speaks coffeescript - but I can't see it, and don't know how to find it!

**Comment by bergie** [comment]
We now show full stack trace in the debug bar in #839 

![screenshot 2018-03-29 at 13 11 58](https://user-images.githubusercontent.com/3346/38085966-e34bc794-3352-11e8-8d66-09bcd53fad2c.png)
