### ISSUE TITLE
ff - breadcrumb route to component source not getting picked up

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#255]
https://github.com/noflo/noflo-ui/blob/cd392fd2ad5f1a557c1a930da15bf6e9a5e20585/elements/noflo-context.html#L126 is setting the window hash, but not showing the component editor. Opening from project panel works.

**Comment by jonnor** [comment]
I can get to the component editor with latest Firefox and app.flowhub.io without issue. Closing as fixed.
