### ISSUE TITLE
Workflow: Example -> own project on github

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#272]
We'd like to have a strong story for an example-based learning experience with Flowhub. It should be very easy for a user to
- _Find_ examples that are relevant for what he wants to do
- _Setup_ required runtime and component libraries for development
- _Explore_ the examples to understand how the program and components work
  - #277 undo and redo should work
- _Start new_ project based on an example, or _import_ parts of an example into project
- _Share_ project to other devices and people using github
## TODO

Define which issues fit into each section of this story

**Comment by bergie** [comment]
Now it is just [Edit as Project](http://bergie.iki.fi/blog/edit-as-project/), add GitHub repo name, push.
