### ISSUE TITLE
Better styles

### ISSUE THREAD

**Issue by cwohlman** [noflo/noflo-ui#280]
We're working on a noflo-ui fork that we're using for another project, and want to add better/new themes. A big hurdle right now is the way that styles are written in the current noflo-ui.

Most elements have been styled directly, I presume in order to speed up the development process. I'd like to split those styles out into css classes so that common ui styles are kept in a central location and can be easily changed by adding a theme class to the document body.

Are you guys interested in a pull request with those changes? If I can make those changes I think they would be beneficial to noflo-ui, and would reduce the effort on people trying to add/modify noflo-ui themes.

**Comment by bergie** [comment]
#814 introduced CSS variables, so we're soon a lot more stylable.

See the difference between light and dark:

https://github.com/noflo/noflo-ui/blob/4808e2c20bcb58f36fa24424cf2f0157f249db90/css/noflo-ui.css#L11
