### ISSUE TITLE
Cannot require any dependencies from custom component

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#281]
To reproduce:
- Create a new component
- Attempt to require one of the dependencies/libs that are included in the preview
  Examples: require 'superagent' or require "visionmedia-superagent/lib/client.js"
  ->
  Error: Error: Failed to require "request" from "noflo-noflo/src/lib/ComponentLoader.js"

Affects component library workflow (#273)

**Comment by ClashTheBunny** [comment]
I think I'm running into this with just a normal component's javascript dependencies.  Is this the case?
![screen shot 2015-05-07 at 5 24 38 pm](https://cloud.githubusercontent.com/assets/248361/7518157/01a8c97e-f4e2-11e4-8600-c2c2891420da.png)

**Comment by jonnor** [comment]
Probably a NoFlo issue though, since it happens on runtime side. Might have been fixed in 0.5.11 https://github.com/noflo/noflo/blob/master/CHANGES.md#0511-october-23rd-2014

**Comment by bergie** [comment]
This is an implementation detail of whatever runtime you're connected to, not Flowhub.
