### ISSUE TITLE
This is amazing, but it needs more tutorials

### ISSUE THREAD

**Issue by CMCDragonkai** [noflo/noflo-ui#289]
I'm more referring to Flowhub.

It looks like a great way to teach programming.

Right now the tutorials are really basic, is there more coming to show more advanced concepts, perhaps a TODO MVC style thing.

The best example would be something that involves an external data store. Since that would cover all the CRUD apps people do.

**Comment by ryedin** [comment]
examples !== tutorials, guys. 

A tutorial starts with nothing, and slowly adds concepts that build up as you go, bit by bit, with good explanations each step of the way until ending up with the final solution. This is what is needed here. You have something powerful, but it's a pretty huge departure from the normal way of doing things. You need to spell out all the gotchas and pitfalls (the concept of groups, for example, needs its own tutorial series for the beginner)

Publishing examples is good also, but don't mistake that for publishing tutorials.

Tutorials are much more valuable than examples.

**Comment by bergie** [comment]
https://noflojs.org/documentation/ was revamped earlier this year. That should be a good start
