### ISSUE TITLE
Do not require 'id' in network runtime messages

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#293]
The 'id' is redundant because it will typically (always?) be "$src.node $src.port -> $tgt.port $tgt.node", and all this information is already transmitted.
It is also ambigious: how much whitespace should there be around node, port and the arrow? Should port names be uppercased or not?

Lets please just get rid of it in the protocol, and let the UI create an .FBP like representation if it so desires.

**Comment by schmurfy** [comment]
I stumbled upon this and even knowing how the id should be formatted I still can't figure out why the data is not showing in the UI. I tried in lowercase, uppercase, with and without the library and still nothing shown :(
