### ISSUE TITLE
Add support for JSX/Harmony in addition to JavaScript and CoffeeScript

### ISSUE THREAD

**Issue by subtleGradient** [noflo/noflo-ui#300]
Cf. http://facebook.github.io/react/blog/2014/07/17/react-v0.11.html#jsx

In HTML…

``` html
<script type="text/jsx;harmony=true">
() => {}
</script>
```

Or…

``` js
JSXTransformer.transform("() => {}", {harmony:true}).code
```

**Comment by jonnor** [comment]
What is required as a minimum for this to work? Loading and sving the files out with .jsx extension?
And for "proper" support, having noflo-browser do these transformations automatically when receiving new/changed components? (for live-programming)

**Comment by subtleGradient** [comment]
Since adding this forever ago, Facebook and the rest of the JS community has moved over to Babel for all our transpiler needs. Please add support for that. See babeljs.com for more info

**Comment by bergie** [comment]
There were pull requests opened for noflo-ui #498 and NoFlo noflo/noflo#294 to add babel support. @subtleGradient can you check if these do what is needed, or if some additional work is required for JSX?

**Comment by subtleGradient** [comment]
Babel isn't enough to properly support JSX. You'll also need to be able to import React in some way. e.g.

    var React = require('React');

**Comment by jonnor** [comment]
On the noflo+ui side we already have React installed. Also on the runtime side, the noflo-browser runtime used by default has React built in. Anything particular setup needed besides that?

**Comment by bergie** [comment]
NoFlo 0.5.14 was just released with babel support.

**Comment by subtleGradient** [comment]
w00t!

**Comment by bergie** [comment]
This totally depends on runtime. We have ES6 with component template for NoFlo now
