### ISSUE TITLE
Gesture based component instantiation.

### ISSUE THREAD

**Issue by alfa256** [noflo/noflo-ui#32]
Instantiate common components and trigger common actions by drawing on the canvas.
Examples:

* `o` shape for a generic component ( opens the search results to type in )
* `<` shape for a Split component.
* `>` shape for a Merge component.
* triangle  for running the graph.

**Comment by jonnor** [comment]
I think this is an idea worth prototyping/playing with.
But since no-one has put work into it for 1.5+ years, gonna close this issue.
