### ISSUE TITLE
Node inspector: more intuitive Clear Error Log UI

### ISSUE THREAD

**Issue by automata** [noflo/noflo-ui#342]
Someone has to use tooltip to know about it. A more intuitive UI/icon possibly helps. Does it makes sense to move it to undo/autolayout panel?

![captura de tela 2014-09-12 as 20 35 25](https://cloud.githubusercontent.com/assets/49062/4258598/1ae4a26c-3ad6-11e4-9ace-052e07f8f3fa.png)

**Comment by jonnor** [comment]
This issue will go away when/if we implement the global/timeline data inspector #244. Then global search/filter will replace need to clear logs like this.

In the meantime, what we could do is to hide the button when there is nothing to clear.

**Comment by bergie** [comment]
Until we have the global inspector, here is how it looks like with #839 

When we have a process error:

![screenshot 2018-03-29 at 16 34 29](https://user-images.githubusercontent.com/3346/38094824-290fde98-336f-11e8-988e-6d5a4cb29d96.png)

After clicking "clear":

![screenshot 2018-03-29 at 16 34 38](https://user-images.githubusercontent.com/3346/38094835-2ee72f4c-336f-11e8-8280-5a1a495e62a0.png)
