### ISSUE TITLE
Components library: sometimes doesn't load

### ISSUE THREAD

**Issue by automata** [noflo/noflo-ui#344]
Sometimes, right after a project is loaded, components library doesn't loads (i.e. when searching for components, nothing is displayed). If the loaded graph has nodes (non-zero graph), it displays just the components which were used on graph:

![captura de tela 2014-09-12 as 20 55 18](https://cloud.githubusercontent.com/assets/49062/4258753/16166f06-3ad9-11e4-909d-538af4300faa.png)

If I reload browser, library loads as expected.

**Comment by ilanbiala** [comment]
@forresto any progress on this?

**Comment by jonnor** [comment]
@bergie did lots of work on this the last couple weeks. Issues should be mostly gone now in git master (will be 0.11). Create new bugs with specific steps to reproduce if any issues remain.
