### ISSUE TITLE
Cannot return from component code in live mode

### ISSUE THREAD

**Issue by djdeath** [noflo/noflo-ui#369]
The search box polymer element still has some assumptions about how to go back from the component view to the containing graph.
One of them is related to the fact there must be a project, but there is also a problem with the url itself (it will likely loose the /#runtime/endpoint?protocol=websocket&address=ws%3A%2F%2Flocalhost%3A5555 part of it).

**Comment by bergie** [comment]
As a workaround, browser back button works
