### ISSUE TITLE
Move runtime discovery down to fbp-protocol-client

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#377]
noflo-runtime is our runtime abstraction layer, and should contain discovery as well as the protocol implementations. Flowhub, mDNS (#205), MicroFlo serial/USB devices, and the local iframe should all be discovered through a common interface.

**Comment by jonnor** [comment]
Vast majority of noflo-runtime has been moved into (the less confusingly named) https://github.com/flowbased/fbp-protocol-client

**Comment by bergie** [comment]
So with runtimes, there are several ways user should get access to one:

* Default runtime(s) for Flowhub like the hosted NoFlo browser runtime
* Runtime registered through the Flowhub registry
* Runtime registered by adding manually
* Runtime registered through a live mode URL
* Attached USB device
* Bluetooth discovery (including [physical web](https://google.github.io/physical-web/))
* mDNS discovery

Some of these we can do directly with a browser. For the things that need lower-level hardware or network access we can build a browser extension that we can [talk with](https://developer.chrome.com/extensions/messaging).

A consideration would be to differentiate between persistent runtimes, like something deployed on a server somewhere, and transient ones like a currently attached USB device.

**Comment by bergie** [comment]
Out of scope since we're limited by browser sandbox.
