### ISSUE TITLE
graph runs automatically when I change IIP values

### ISSUE THREAD

**Issue by akonsu** [noflo/noflo-ui#383]
On flowhub.io, if I create a graph, and then run it (by clicking the triangle arrow that says "connected"), the UI gets into a state where any edits to the graph's initial values result in a new run immediately after the IIP edit box loses focus.

I expected:
1. run the graphs only when I click the "connected" button
2. otherwise, have a way to get into the initial state where the graph does not run autonomously

If my expectations are wrong, would you please explain the reasoning behind this behaviour?

**Comment by jonnor** [comment]
This behavior is partially up to the runtime (ie. NoFlo). But in general, when the runtime is "running" or "started", then changing an IIP sends the IIP to the process immediately, and this triggers further processing.

To avoid this happening automatically, one can hit the "pause" button to stop the runtime. Changes made in this state are not sent immediately to the process, at least by NoFlo. Then one can hit the "play" button to start the runtime again.
