### ISSUE TITLE
graph executes as many times as there are previous runs

### ISSUE THREAD

**Issue by akonsu** [noflo/noflo-ui#384]
This relates to https://github.com/noflo/noflo-ui/issues/383:

When I open a graph, and run it several times in a row (say, click the "connected" button 3 times), and then change one of the graph's initial values, the graph runs automatically the same number of times. Not just once, but a few times in a row  (3 times if I clicked the button 3 times before). Is this the way it is supposed to be?

**Comment by ryedin** [comment]
confirmed similar behavior in my project (FWIW)

**Comment by jonnor** [comment]
No it should run only once. What runtime are you using? noflo-browser?

**Comment by akonsu** [comment]
I use nodejs runtime. I used "math" components connected to the "output" component. I judged about the number of runs based on the number of outputs. I think it is related to that the components do not reset the state when the graph is stopped so it appears that the graph is run several times.

**Comment by ryedin** [comment]
ditto, nodejs runtime.

**Comment by ryedin** [comment]
@jonnor can you confirm for us whether you'd expect this behavior if components aren't properly cleaning up/disconnecting?

The whole "when to call disconnect" thing is certainly something that's confusing me. When I look at the source of many of the core components I see a mixed bag as far as when disconnect is explicitly called vs just forwarded from in ports. Should we disconnect after every send? Is this even potentially related to this issue? (...where oh where are all the great user tutorials we should have by now? </whiney voice>)

**Comment by jonnor** [comment]
Most components are state-free and should not remember previous "firing".
Not sending disconnect may prevent the network from stopping, but the old
network should be thrown away when doing stop/start again anyway.

Disconnect should be sent in component when it has stopped sending packets,
and new packets will not be sent until there are new packets coming in.

**Comment by akonsu** [comment]
for example, noflo-math does not clean up primary and secondary values on shutdown, and since it invokes `calculate` when either primary or secondary data are received (e.g. https://github.com/noflo/noflo-math/blob/master/lib/MathComponent.coffee#L36) I see two results for add, sub, etc. on subsequent runs. this is perhaps I mistook it for multiple runs.

**Comment by jonnor** [comment]
Ok, so if anything this is a `noflo-math` issue. Feel free to open an issue there.
