### ISSUE TITLE
In live mode, data types of ports with IIPs get lost

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#391]
Prerequsite: imgflo or noflo-nodejs runtime running default graph, nodes have non-string IIPs attached (for instance numbers)

To reproduce: Connect in live mode, click node, observe types of IIP editors for ports with value
Expected: IIP editor reflects port type as specified by component
Actual: IIP editor is always string

Removing and re-adding a node of an affected component does not change anything. Value seems cached somewhere.

**Comment by 7yl4r** [comment]
If I'm understanding this issue correctly, it's easy to see using canvas/MakeRandom, the numbers put in are parsed (and then added) as strings, so MakeRandom(min=1, max=2) always results in something like 10.2342356098.

**Comment by 7yl4r** [comment]
Also worth noting here that strings/ParseJson is a useful workaround.

**Comment by 7yl4r** [comment]
I'd like to work on this issue, but I'm having a hard time getting into the code, any tips?

**Comment by 7yl4r** [comment]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=5858790)](https://www.bountysource.com/issues/5858790-in-live-mode-data-types-of-ports-with-iips-get-lost?utm_source=5858790&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by bergie** [comment]
Doesn't seem to be an issue any longer
