### ISSUE TITLE
Support a graph that spans multiple runtimes

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#392]
One of the power of the graph framework is that a graph could span multiple runtimes. This is a powerful application for IoT use cases. One way the editor could support this is via a MultiRunTime (MRT). One would select this as the main runtime for the project.

The MRT would list list all available runtime as groups in the component browser and the components of them as well. It would need to ensure to list components just once (what about different versions?).

The user would need to first instantiate groups for each runtime to use. Components can only be instantiated in a group that actually has them. Not sure if we can auto-instantiate the group the first time a component is created (this won't work if multiple runtimes offer the same component).

A hierarchical list in the component browser, that groups components by they runtime might be an alternative. This way we won't need to dedup the components and its clear in which runtime they would run. When filtering we'd need to show them together with the runtime header to make the results obvious.

**Comment by bergie** [comment]
@ensonic real-world example: https://github.com/c-base/ingress-table/blob/master/package.json#L63

The remote MicroFlo runtime there becomes a `runtime/PortalLights` component available to NoFlo. The component becomes `ready` when connection has been established successfully to the microcontroller.

Same would work with WebSockets to Node.js/JavaFBP/whatever runtimes.

**Comment by jonnor** [comment]
@ensonic Work has started on a "pseudo" runtime, where the individual component/nodes are separate processes (potentially on different machines) which communicate through messaging queues. AMQP and MQTT are the initially supported transports.
https://github.com/the-grid/msgflo

**Comment by ensonic** [comment]
@bergie are there more such examples or doc? I have tried adding http://fpaste.org/181354/55739142/ this to the package.json of my nodejs-runtime but no runtime/* shows up.

**Comment by jonnor** [comment]
@ensonic There are some testcases here: https://github.com/noflo/noflo-runtime/blob/master/spec/RemoteRuntimes.coffee
We made some changes on noflo-runtime side (client) when deploying the ingress-table (MicroFlo as remote runtime in noflo-nodejs), it could be that noflo-runtime-websocket needs updating to match.

**Comment by ensonic** [comment]
@jonnor thanks, but still no luck :/ I'll dig the history of the ingresstable module.

**Comment by jonnor** [comment]
@ensonic do the tests fail or pass for you?

**Comment by ensonic** [comment]
@jonnor not all of them:
'''
  Remote runtimes
    PseudoRuntime over WebSocket in NoFlo
      ✓ should be instantiable 
      ✓ should set description 
      ✓ should populate ports and go ready after connecting to remote 
SENC: ignoring event type connect
      ✓ sending data into local port should be echoed back 
    MicroFlo simulator direct in NoFlo
      ✓ should be instantiable 
      ✓ should be possible to upload new graph 
      ✓ should have exported inport and outport 
SENC: ignoring event type connect
WARN: ignoring sendPacket during graph upload
      1) sending data into local port should be echoed back
    NoFlo over Websocket in NoFlo
3891 null
      ✓ should be instantiable 
      ✓ should be possible to upload new graph 
      ✓ should have exported inport and outport 
SENC: ignoring event type connect
Fatal error: Cannot read property 'processes' of null
'''

**Comment by ensonic** [comment]
Just to clarify my setup:
On the Lego EV3 I run a noflo-nodejs runtime with a bunch of component libraries.
On my beaglebone BBB I run a  noflo-nodejs runtime with a bunch of component libraries.

On the EV3 I added a <root>/graph/export_accel.json that is a graph for the BBB. Also on the EV3 I added the remote runtime to the toplevel package.json (the one of the runtime that previously did not even have a noflo section).

With app.flowhub.io I connect to the EV3 and open a graph on the ev3. I expect "runtimes/xxx" among the components where xxx is the remove runtime graph. Right?

**Comment by jonnor** [comment]
The failing test is likely at core of issue... Unable to have a look right now.

In noflo-nodejs executable, exceptions are swallowed by default. Try disabling that (inside bin/noflo-nodejs), and see if you get any errors.

Another caveat: The runtime that refers to a remote runtime must be able to connect to it during startup.

**Comment by jonnor** [comment]
[MsgFlo](http://github.com/msgflo/msgflo), the FBP runtime where each node can run on separate devices communicating using a message broker, is now in a pretty useful state.
There is [support for multiple languages](http://www.jonnor.com/2015/06/announcing-msgflo-a-distributed-fbp-runtime/) (JS/node, Python, C++) and multiple transports (AMQP, MQTT).
We're using it in production at TheGrid (with AMQP), including in [imgflo-server](http://github.com/jonnor/imgflo-server).

Each of these nodes can either be implemented as FBP, or plain-old-imperative-code - as long as they send the right discovery messages.

For instance at c-base, we used it to connect a bunch of existing software (mostly microcontrollers with software written in C, I think) in new ways, including wiring through a NoFlo graph (running on another device).
https://github.com/c-base/c-flo
https://plus.google.com/events/c532t23tqd6h901i3f6hv81mlps/100751105859582805241/6202307522901306658

There are still things missing, like being able to 'forward' FBP runtime communication, such that one can do 'open subgraph' and be able to go from the MsgFlo to NoFlo level.

**Comment by bergie** [comment]
[MsgFlo](https://msgflo.org/) is pretty much the solution there. Recent versions are fully live-programmable from Flowhub.
