### ISSUE TITLE
Move error notifications to in-browser panels

### ISSUE THREAD

**Issue by automata** [noflo/noflo-ui#399]
Instead of the usual error notifications...

![captura de tela 2014-11-14 as 15 20 54](https://cloud.githubusercontent.com/assets/49062/5052835/8d7d868c-6c2b-11e4-899d-a9d16b25f985.png)

... maybe we could have them as in-browser alerts like the "loading" one.

**Comment by bergie** [comment]
This is implemented in #839 via the right-hand bar showing runtime events and errors:

![screenshot 2018-03-29 at 13 14 00](https://user-images.githubusercontent.com/3346/38086004-18dd87da-3353-11e8-831d-037b99b73d3b.png)
