### ISSUE TITLE
offer https

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#402]
On loading http should offer to switch to https. Can't redirect for now, bc local projects would be lost. Should encourage people to sync what they want to keep with GitHub.

**Comment by rhalff** [comment]
I've tried to make it easy to setup `wss` for local noflo-nodejs installations:

The pull request is overhere: https://github.com/noflo/noflo-nodejs/pull/11

The main issue I found is once the local server is running you will first have to accept the
certificate within the browser, confirming you trust yourself, so I've made this possible by having the https server reply with a simple 'OK' message.

Flowhub is then able to connect to the wss server and correctly detects the runtime.

For valid certificates which are located at another location, I would suggest symlinking the files within ssl/ to the valid certificate locations. (not tested)

I've added some extra info to the README on how to generate a certificate:
https://github.com/rhalff/noflo-nodejs
