### ISSUE TITLE
Keep a selected runtime for a project

### ISSUE THREAD

**Issue by automata** [noflo/noflo-ui#405]
I have a project recently cloned from gh. It's default runtime is `iframe`. I set up a `nodejs` runtime to work with it and selected this new runtime on a graph of the project. Now, every time I open a subgraph of that project or reload it, I have to select the new runtime again. Is it supposed to store the last selected runtime and set it to all subgraphs of the project?

**Comment by bergie** [comment]
Right now runtime selection is on per-graph level, but indeed project level would make sense

**Comment by jonnor** [comment]
Use 'project runtime' as long as it is of compatible `type` for the graph
