### ISSUE TITLE
Show a remote runtime node slightly differently

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#407]
Currently they look identical to "normal" nodes. Things to maybe visualize:
- connected / ready-state.
- type of runtime
- the address

**Comment by bergie** [comment]
This is a special noflo-runtime feature. I don't think it makes sense to implement here.

However, it would be useful to know process activation/deactivation status, for example with MsgFlo.

**Comment by jonnor** [comment]
When we can have multiple runtimes with protocol forwarding it will come up again. But we can deal with it then
