### ISSUE TITLE
shouldn't go home after synchronizing

### ISSUE THREAD

**Issue by automata** [noflo/noflo-ui#412]
After clicking the `Synchronize` button, Flowhub reloads and shows the home screen.

![sync-repos](https://cloud.githubusercontent.com/assets/49062/5247717/06b9212c-795c-11e4-9d4f-826f636d9d3a.gif)

**Comment by forresto** [comment]
Especially annoying b/c the url hash doesn't change, so clicking back to the project doesn't load it.

**Comment by automata** [comment]
Maybe forcing a reload can solve.

**Comment by forresto** [comment]
:trollface:

**Comment by bergie** [comment]
Basically the problem is that we get a "state OK" message that doesn't have what https://github.com/noflo/noflo-ui/blob/master/elements/noflo-ui.html#L334 expects to get

**Comment by 7yl4r** [comment]
it looks like `this.ctx.graphs` is emptied somewhere, but my meager debugging attempts have been unable to track down where or what to do about it.
