### ISSUE TITLE
github permissions

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#413]
Logged in, then log out, then log in again. Github asks to modify permissions from private to public:

![screen shot 2014-12-10 at 10 22 35 am](https://cloud.githubusercontent.com/assets/395307/5378196/7e6b8614-8056-11e4-9c8c-2a3924d1d71c.png)

Then settings > Flowhub plan > :arrows_counterclockwise: asks to login again:
![screen shot 2014-12-10 at 10 26 32 am](https://cloud.githubusercontent.com/assets/395307/5378333/60b1d0d2-8057-11e4-95d6-43427db05c28.png)

And Github asks for private access again.

This seems by design, as the first login goes through `Login` and asks for `github_public`. The second (once user is identified as backer) goes through `ProLogin` and asks for `github_private`.

UserStorage graph:
![screen shot 2014-12-10 at 10 19 30 am](https://cloud.githubusercontent.com/assets/395307/5378157/3c6727fa-8056-11e4-8d0e-8db0460808b5.png)

Fixing it would require knowing if user is a backer before asking Github permissions for the first time, which would be a pretty big change to the login flow. 

It is one of those "need to refresh" bugs.

**Comment by forresto** [comment]
Now there are different apps for Flowhub:
![screen shot 2015-02-18 at 1 19 40 pm](https://cloud.githubusercontent.com/assets/395307/6253643/facc11b4-b770-11e4-9018-c6d53f0b32e8.png)

**Comment by jonnor** [comment]
@forresto Does this mean we can close this issue?
Seems elated to #432
