### ISSUE TITLE
UI for deleting manually added runtimes 

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#417]
As flowhub had issues showing my runtimes I added it manually a few times. Now I'd like to remove some of them as well.

**Comment by bergie** [comment]
You can make a `HTTP DELETE` call to `/runtimes/<UUID>`. Remember to use HTTP Bearer authentication with your Grid token!

**Comment by ensonic** [comment]
I know, still it would be nice to offer that from the UI.

**Comment by bergie** [comment]
@ensonic yep, that is why I kept the issue open :-)

**Comment by ensonic** [comment]
Seems to be not that simple. I guess token != uuid-of-user
```
$ curl -X DELETE "http://app.flowhub.io/runtimes/<uuid-of-runtime>" -H "Authorization: Bearer <uuid-of-user>"
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Regarding the UI. What about changing the "Register" button on the front-page to "Manage". In the follow up dialog, next to "Add manaually" have a "Remove" button. Clicking this will bring up a list of runtimes and one can multi-select and remove them. Sounds like a plan?

**Comment by ensonic** [comment]
Okay I figured: you open the dev-console, set a breakpoint to e.g. index.js:676, go to setting and copy the token from the inspector. Meh. Lets fix the UI :)

**Comment by bergie** [comment]
@ensonic we have designs for new NoFlo UI homescreen that will allow us to provide delete buttons next to runtimes, projects, etc. But might take a while before we have time to implement

**Comment by chadrik** [comment]
+1
@bergie, is there an easier way to get the grid token than setting breakpoints in chrome?  It worked, by the way, so big thanks to @ensonic.  The line number changed, so for future readers of this thread, the line you're looking for is `dialog.gridToken = this.gridToken;`

**Comment by chadrik** [comment]
Hi @bergie and @jonnor, would love an answer to this question.  Thanks.

**Comment by bergie** [comment]
@chadrik you can find it from localStorage in developer tools

**Comment by RuRu92** [comment]
This is still no implemented and it's been over a year now?! This is rather annoying

**Comment by sejnub** [comment]
I am working on a docker image for the noflo-js runtime. While I tested it I produced a lot of runtimes which now clutter my UI. 

So I +1 this enhancement.
