### ISSUE TITLE
in-ports should only allow one input

### ISSUE THREAD

**Issue by chadrik** [noflo/noflo-ui#423]
To reproduce:
- created two Repeat nodes and one Add node
- connect the out port of the first Repeat node to Add.augend
- connect the out port of the second Repeat node to Add.augend

There are now two connections to Add.augend.  There should only ever be one input to a non-array port, right?

**Comment by bergie** [comment]
No, ArrayPorts support addressable connections (`in[0]`, `in[1]`, etc). For non-ArrayPorts, multiple connections are fine but they shouldn't be able to distinguish which connection the data came from as they should be treated the same.

See noflo/noflo/#90 for a longer discussion about this

**Comment by chadrik** [comment]
Thanks for the link.  That looks like a very informative discussion.  It's on my reading list.
