### ISSUE TITLE
port gets connected when dragging component's pie menu

### ISSUE THREAD

**Issue by akonsu** [noflo/noflo-ui#424]
1. right click on a component to bring up the pie context menu
2. move the mouse over one of the ports shown around the menu, and try to drag the rectangle that represents the port
3. observe that the rectangle does not move but the editor workspace moves along with the graph in it (this is correct)
4. release the mouse to stop dragging, and observe that after you move the mouse you get a dangling connector attached to this port as if you started connecting the port by dragging it from the component.

**Comment by bergie** [comment]
This is an upstream bug in https://github.com/flowhub/the-graph

Please file there as needed.
