### ISSUE TITLE
Missing lint CSS from CodeMirror

### ISSUE THREAD

**Issue by bergie** [noflo/noflo-ui#430]
On app.flowhub.io:

![screenshot 2015-01-23 at 19 06 39](https://cloud.githubusercontent.com/assets/3346/5879848/0785eda0-a333-11e4-88d7-91e3f45c832d.png)

cc/ @forresto

**Comment by forresto** [comment]
Fixed: https://github.com/noflo/noflo-ui/commit/fa0d6ebff2a728e5e49d160751e903404d85ec34#diff-a35864fcc4749a3b904641b4be9feacfR191
