### ISSUE TITLE
check gh token between server and client

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#432]
Logging in http and then switch to https can result in 'bad credentials' response from GitHub and silent fail in noflo-ui. 

Should check on startup.

Dumb fix: Log out / log in / settings > refresh / relogin

**Comment by jonnor** [comment]
@forresto is this still an issue?

**Comment by bergie** [comment]
Fixed in 0.16.0:

https://github.com/noflo/noflo-ui/blob/master/CHANGES.md#0160-2017-february-17
