### ISSUE TITLE
'definition is not defined' in base.coffee from noflo-noflo's runtime

### ISSUE THREAD

**Issue by ComFreek** [noflo/noflo-ui#436]
- Code
 Branch `master`, commit `ffd2c59676968f62d612db80eab18ded3163bdea` (the latest one as of  January 31, 2015). Branch `dev` doesn't seem to contain any relevant commits for this bug.

- Tested with Google Chrome and IE.

### Steps to reproduce

1. Start `grunt build` and `grunt devp` (or `simple-server`)
2. Open NoFlo-UI in the browser.
3. Open an example project or create a new one. Both actions trigger the opening of a project, which is that part that fails.

The exact error message in Chrome:

```
noflo-ui.js:25301 Uncaught ReferenceError: definition is not defined
```

### Solution suggestions
The error message is without JS source maps of little help, of course.
Searching the whole `noflo-ui` folder for the keyword `BaseRuntime` yields only one file: `noflo-ui\components\noflo-noflo-runtime\src\runtimes\base.coffee`.

Here is the relevant part (ll. 1 - 6) of this file:
```
platform = require '../platform'

class BaseRuntime extends platform.EventEmitter
  constructor: (@definition) ->
    @definition.capabilities = [] unless definition.capabilities
    @graph = null
```
I have never worked with CoffeeScript, but I guess (and CoffeeScript's docs confirm that observation) that there is a missing `@` sign in front of `definition.capabilities`.

I would have opened a pull request if I had found the file in this repository. How is this file created by the build script?

**Comment by mc007** [comment]
same here, just installed as said: stuck with loading scene, same error in chrome

**Comment by jstriebel** [comment]
I can also confirm this.
@ComFreek: The code for this is in another repository that is pulled into the project by grunt (see https://github.com/noflo/noflo-ui/blob/b38432a28638127e328f475bf5370b38ff0dfea6/component.json#L29)
I submitted a PR (is linked above) with your fix.

**Comment by bergie** [comment]
Fix merged to noflo-runtime.
