### ISSUE TITLE
runtime selector needs better colors

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#438]
Due to the chosen colors, one needs to hoved them one by one to find them.

![screenshot from 2015-02-06 12 28 59](https://cloud.githubusercontent.com/assets/1279486/6078685/beeeb724-adfb-11e4-8371-dae745a6a5c8.png)

**Comment by bergie** [comment]
Looks like this now:

![screenshot 2015-03-02 at 18 49 04](https://cloud.githubusercontent.com/assets/3346/6446678/f7cde6fe-c10c-11e4-89c3-432b11489c7a.png)

**Comment by automata** [comment]
Much better!
