### ISSUE TITLE
weird error messages from runtime?

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#440]
Can we do better here? What is actually wrong? What am I supposed to do to fix it?

![screenshot from 2015-02-06 15 14 56](https://cloud.githubusercontent.com/assets/1279486/6080597/28eef7bc-ae13-11e4-8d01-e1926a150d47.png)

**Comment by ComFreek** [comment]
:+1: The biggest problem in my opinion is that the errors are not logged in the browser's console. Therefore, neither stack traces nor file names are shown!

**Comment by ensonic** [comment]
It seems these come from graph loading and inturn the root issue is that the components are not queried. When this happens the component list on the left only has the items listed that are part of the graph.

**Comment by ensonic** [comment]
The green lines should be what the editor sends to the runtime, right? e.g.
'''
{"protocol":"component","command":"list"}
'''
And the white ones the reply?
'''
{"protocol":"component","command":"component","payload":{"name":"Graph","description":"","subgraph":true,"icon":"sitemap","inPorts":[{"id":"graph","type":"all","required":true,"addressable":false,"description":"NoFlo graph definition to be used with the subgraph component"}],"outPorts":[]}}
'''
Shouldn't that start sending the components? What could it cause to not do that? Please.

![screenshot from 2015-02-06 19 09 59](https://cloud.githubusercontent.com/assets/1279486/6084729/cbd91816-ae33-11e4-8311-f2136a886026.png)

**Comment by ensonic** [comment]
Mystery solved. I switched to use PROJECT_HOME (see https://github.com/noflo/noflo-nodejs/blob/master/index.js#L36-37) to be able to move my flowhub.json out of the runtime package directory. This also caused nodejs to use PROJECT_HOME to for component loading :/
