### ISSUE TITLE
Trouble building noflo-ui 

### ISSUE THREAD

**Issue by darmie** [noflo/noflo-ui#442]
I have tried building noflo-ui according to the guide but some components  are not installing. 
components like noflo-polymer.. also i am seeing errors that points to IndexdDBShim

**Comment by forresto** [comment]
Sounds like you didn't get the bower dependencies. `grunt build` should install them. Try `bower install` to see if that works.

**Comment by forresto** [comment]
Actually sounds more like component.json deps. There is a bug that something fails during component(1) install then it can't recover. Try `grunt rebuild` which will clean up the dependencies and try again.

**Comment by darmie** [comment]
Thanks for the quick response @forresto , I used grunt-build, but i get this 
`Warning: EPERM, symlink 'c:\Users\Darmie\documents\gamedev\proj-dragonfly\compon
ents\noflo-noflo-polymer\noflo-polymer\noflo-polymer.html' Used --force, continu
ing.`

**Comment by darmie** [comment]
@forresto I tried your solution `grunt rebuild` build still failing. I am getting this `Warning: EPERM, symlink 'c:\Users\Darmie\documents\gamedev\proj-dragonfly\app\no
flo-200.png' Used --force, continuing.`

Also when i try to run it in browser via simple-server, some files are still missing, so noflo-ui is still somehow broken and nothing seem to be working

**Comment by ComFreek** [comment]
1. Run the console with admin privileges and then run `grunt rebuild`.
2. I had similar errors a while back, re-running the commands solved the problem.

**Comment by darmie** [comment]
@ComFreek I am running the build inside git terminal on a windows (8.1) PC. How do i run it with admin priviledges?

**Comment by ComFreek** [comment]
@darmie Do you really Need to use Git Terminal? If not, you can open Explorer at noflo's root folder, click on the menu, hover over the cmd or PowerShell Icon and select 'Run as admin'.

Note that my installation also needed another tweak in the Gruntfile.js: https://github.com/noflo/noflo-ui/pull/435/files

**Comment by darmie** [comment]
`Done, without errors` Thank you @ComFreek .

**Comment by ComFreek** [comment]
You're welcome.

@forresto BTW, I have already submitted a PR for this: https://github.com/noflo/noflo-ui/pull/434
