### ISSUE TITLE
Build based on .fbp files instead of .json files

### ISSUE THREAD

**Issue by vcharpenay** [noflo/noflo-ui#447]
When one woks on graphs in Flowhub, changes are saved in .json files (in the `/graphs` folder). However, noflo-ui's build parses .fbp files instead of .json files, where no change appears. Is it configurable?

This issue is maybe more related to [noflo/grunt-noflo-browser](https://github.com/noflo/grunt-noflo-browser), however.

**Comment by jonnor** [comment]
NoFlo supports loading both .json and .fbp files (through http://github.com/noflo/fbp), out of the box.
Flowhub / NoFlo UI only supports exporting .json files.

Does this answer your question?

**Comment by vcharpenay** [comment]
Well, not exactly. Sorry I've not been clear.
I branched noflo-ui and started to add some features. I wanted to use FlowHub itself to modifiy its graphs. However, the changes I make on FlowHub are exported in .json files. Since the build is based on the .fbp files, my changes are not taken into account and I have to manually incorporate them into the .fbp files. I guess full-time FlowHub developers don't do that. Is it possible to build directly on the .json files? Or do you have a simpler methodology?

**Comment by bergie** [comment]
@vcharpenay Flowhub didn't support editing itself when we made the graphs. I think we should migrate them all in JSON here soon

**Comment by vcharpenay** [comment]
Alright, thanks. I like the FBP grammar, though. It is more convenient than JSON (but maybe less functional).
