### ISSUE TITLE
RFC: a graph wide configuration

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#448]
One issue that clutters graphs is when multiple nodes need the same IIPs. What about having a configuration as in a key-value storage. Whenever entering values in the port editor on the top-left of the noflo-ui, also allow to select from the configuration via popup/dropdown.

When editing the configuration, the UI could e.g. use colors to highlight ports that use the value.

**Comment by bergie** [comment]
Somewhat related: #288

**Comment by ensonic** [comment]
Closing in favour of #464.
