### ISSUE TITLE
dropping subgraph onto itself explodes the universe

### ISSUE THREAD

**Issue by ryedin** [noflo/noflo-ui#452]
I only did this by accident (was trying to choose a different component and clicked the same subgraph I was working on)

noflo-ui seemed OK with it, but it annihilated my runtime (nodejs), which spat out a few hundred of the following lines and then crashed.

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
```

Seems maybe the ui needs to filter the component list to prevent this type of recursion from happening.

**Comment by bergie** [comment]
This was fixed in #95 but seems like we have a regression. See also noflo/noflo#147

**Comment by ryedin** [comment]
My apologies again for the issue duplication, will try to do a better job searching existing issues going forward...

**Comment by bergie** [comment]
@ryedin no problem, in this case we already fixed it once, but there was a regression. So new issue is OK :-)
