### ISSUE TITLE
component loading from nodejs-runtime hangs on first load

### ISSUE THREAD

**Issue by ryedin** [noflo/noflo-ui#459]
Potentially related (similar behavior) to: https://github.com/noflo/noflo-ui/issues/455

On first attempt at loading a subgraph I still get the orange 'Loading...' header bar that hangs. Eventually I get the following error in the browser console:

```
WebSocket connection to 'wss://api.flowhub.io/primus/?_primuscb=1425952125910-1' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

However, now if I refresh, the subgraph I was attempting to load is visible, and then navigating back and even opening other subgraphs and components seems to work fine.

**Comment by automata** [comment]
I'm not sure if totally related, but when trying to connect to a nodejs runtime with new or changed components, the components on noflo-ui didn't get updated as expected.

As far as I remember, the steps to reproduce are:
1. Pull the same repository on noflo-ui and on git CLI
2. Setup the nodejs runtime on your local repository
3. Change some component source code on the local repository
4. Connect noflo-ui (Flowhub) to the runtime
5. Changes made on component source code should be reflected on noflo-ui but they're not

Specially things like components inport/outports lack updates, but also new components itself are not created on noflo-ui.

**Comment by jonnor** [comment]
@automata I suspect that is another/special case of that in project-mode we don't respect changes coming from the runtime. Mostly tracked in #443

**Comment by bergie** [comment]
Unable to reproduce
