### ISSUE TITLE
Faulty jump back to home screen after Github sync

### ISSUE THREAD

**Issue by ijsf** [noflo/noflo-ui#460]
Found a minor issue when syncing with GitHub:

1. Create a project on local noflo-ui server.
2. Synchronize project with GitHub repository (configure in Settings, Save and use Synchronize button).

noflo-ui now erroneously jumps back to the home screen, while the URL is still pointing to the project.

To work around this, remove the #... part from the UI and carry on.

**Comment by forresto** [comment]
Dupe #412 🙈
