### ISSUE TITLE
Graphs do not always show up as components

### ISSUE THREAD

**Issue by ijsf** [noflo/noflo-ui#461]
I'm having a pretty major issue trying to find the corresponding component for a graph that I have just imported through GitHub.
1. Create a GitHub repository with an arbitrary noflo .json graph file that resides in the graphs/ directory.
2. Create a project on local noflo-ui server.
3. Synchronize project with GitHub repository (configure in Settings, Save and use Synchronize button).
4. The .json graph should now be available from the left side menu under Graphs.
5. Create a new graph by using the New graph button.
6. Use the Search components window to find the earlier .json graph.

The .json graph will _not_ appear in the components list and can thus not be used/referenced in any other graph.

(Additionally, I added a graph through noflo-ui, which did appear. Though, after deleting the graph it remained in the components list, so something is off here.)

**Comment by ijsf** [comment]
Found the cause by manual debugging using the `noflo` command-line interpreter.

The particular .json graph that I was trying to open was that of the `noflo-automaton` library (`graphs/Automaton.fbp` converted to .json). Unfortunately, this library referenced an old version of noflo (0.4.5). Trying to verify whether the library was working correctly, I used the `noflo list` command in the library's directory, and got the error discussed here for one of the components exposed in the library: http://stackoverflow.com/questions/24295978/noflo-error-typeerror-object-port-arrayport-has-no-method-isaddressable

After updating the noflo dependency, everything worked correctly. Note that at no point, the `noflo-ui` gave any error message, and apparently just failed silently and broke half of the UI.

**Comment by jonnor** [comment]
Afaik, we added the `error` arguments to the ComponentLoader in last version. So now it is mostly about surfacing this error. Probably needs to happen in https://github.com/noflo/noflo-runtime-base as we move the `noflo` tool over to noflo-nodejs (#279).
