### ISSUE TITLE
running status is not updated

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo-ui#462]
I edit my project on a nodejs-runtime, press run, the status should say "running", but it doesn't.
I reload the page, the status says "running".
I stop the graph, the status should say "not started", but it doesn't.
I reload the page and the status got updated.

**Comment by ensonic** [comment]
Seems to be not reproducable today.

**Comment by bergie** [comment]
@ensonic we released a new version yesterday, might've been fixed by that
