### ISSUE TITLE
edited components do not always update in graph

### ISSUE THREAD

**Issue by 7yl4r** [noflo/noflo-ui#473]
I'm seeing this behavior through flohub, but I believe it applies here. Components modified through the in-app editor or by pulling from github will often fail to update on the graph.

To reproduce: add a component to the graph, edit the component to add (or remove) an in or out port.
Expected: component node in graph updates to match the change.
Actual: component will fail to add new ports or remove old ports. In the case of removing ports this sometimes results in a "component does not have port ____" error.

I'm not sure if [this function in the-graph](https://github.com/the-grid/the-graph/blob/6c24c553c08b2415e18e691fc4a57f94fef62ab0/the-graph/the-graph-iip.js#L38-L46) is relevant, or if that function only pertains to rendering.

**Comment by 7yl4r** [comment]
I've noticed the same issue with component/graph descriptions & icons.

**Comment by bergie** [comment]
@7yl4r noflo-ui master and the-grid/the-graph#223 contain some improvements to icon and description handling. I'll see about the component changes next.

**Comment by dmtaub** [comment]
I notice this still happening on flowhub when removing a port added in the online editor. There seems to be nothing short of deleting the project that will allow creation of a node with fewer ports.

**Comment by bergie** [comment]
@dmtaub I think is a bug in library caching in noflo-ui, we only add ports, never remove. Will look at this.

**Comment by bergie** [comment]
Fixed via #839
