### ISSUE TITLE
network data messages

### ISSUE THREAD

**Issue by schmurfy** [noflo/noflo-ui#474]
Hi,
I am currently implementing a new runtime and so far most of the bases works but I was puzzled about the protocol:network, I enabled it and with it responds to the getstatus message but then I looked at the documentation and saw the data message.

I implemented it (at least what I send seems correct) but so far I have yet to find any effect on the ui, does it work ? How and where the data messages should appear ?
I tried to select an edge, a node, nothing... :(
The right panel stays empty and there are no errors on the console.

PS: I tried with flowhub as well the master branch.

**Comment by jonnor** [comment]
The network:data should appear in the left panels of the selected edges.
noflo-ui is currently extremely picky about the `id` values, which is a bug: https://github.com/noflo/noflo-ui/issues/293

**Comment by schmurfy** [comment]
thanks, I will give it a try :)

**Comment by schmurfy** [comment]
I just did some test using the id formatted as mentioned but I still can't make the data appears :/
I already noticed some annoying mixups with library and name in other places (there are already issues open there maybe even by you ^^), in some place you need to include library in the name, others want it in a specific field...

This is a really awesome application but it would be nice to have some debugging message when something is wrong inside os silently discarding messages.

**Comment by jonnor** [comment]
@schmurfy I would recommend introspecting what the WebSocket data from a working runtime looks like (using the Chrome Devtools). http://codetheory.in/websocket-traffic-inspection-in-chrome-developer-tools/

Here is example of the format from working code (a bit verbose since its C):
https://github.com/jonnor/imgflo/blob/master/lib/ui.c#L124

**Comment by schmurfy** [comment]
thanks for the source link, I figured out other things by looking at what is sent by other runtimes but that's annoying :/

**Comment by schmurfy** [comment]
in fact I can't even run any existing runtimes...
I can't build imgflo and the nodejs runtime does not seems to send any data message, I guess I will just concentrate on something else and put the data messages aside for now.

**Comment by jonnor** [comment]
noflo-nodejs should send data messages, assuming there is a running network set up

**Comment by schmurfy** [comment]
Thanks, the graph was not running :p 
I gave another try and now I see what noflo-nodejs sends (and the data messages show on the ui) but still can't manage to reproduce it on my own :\

What are the network:connect and network:disconnect messages supposed to mean ? I tried sending a connect, my data and a disconnect but still not shows up :(

**Comment by jonnor** [comment]
Can you show your graph, and the output of the messages you are sending over WebSocket (from Chrome devtools etc)?

network:connect/disconnect are for indicating start/end-of-transmission for runtimes which have this concept. It works fine without it.

**Comment by schmurfy** [comment]
I checked again every messages sent to avoid wasting your time and I managed to find the culprit, I was sending the graph name alone but it was expecting `<library>/<name>`, I also had the same issue in the getstatus response but I am not sure it does matter as there was no errors.

is there a practical reason to split library and name for some calls instead of always using the "full" name `<library>/<name>` ?

**Comment by jonnor** [comment]
Not that I know of, no, I think its just inconsistencies. We have some bugs filed related to this, like https://github.com/noflo/noflo-ui/issues/411

Anyway, glad you found the issue :)

**Comment by schmurfy** [comment]
Thanks for your help, having the debug messages will really help move forward ^^

**Comment by schmurfy** [comment]
I just updated to the latest release (0.25.1) and this issue came back to bite me again :(

I am using a local copy of noflo-ui and I access it using an url like: http://127.0.0.1:8080/#runtime/endpoint?protocol=websocket&address=ws%3A%2F%2F127.0.0.1:8080

when I am in that state the debug message are shown correctly when I select an edge but I cannot edit anything, now if I click "Edit as project" it takes me to another url which looks like this for me: http://127.0.0.1:8080/#project/e6b6a67d-662c-4af0-8b67-e24fe2d4561c/e6b6a67d-662c-4af0-8b67-e24fe2d4561c%2Fmain

In this state I can edit the graph but the debug message no longer show, if I look at the developer tools I see the message are still sent through the websocket...

is it the normal behavior ?

**Comment by jonnor** [comment]
@schmurfy what runtime are you using (and version)?

When going from edit mode to live mode, Flowhub  sends over the current state as graph messages. I've seen in some cases that the 'network' id changes in this case. Do you see anything like that?
Will need the log of WebSocket messages to be able to help debug this.

**Comment by jonnor** [comment]
I am seeing a related issue with MicroFlo. Data is not shown in edge inspectors when in live mode, but when changing to editor mode they do. So opposite from what you are seeing.

**Comment by schmurfy** [comment]
the runtime is my own but since the data are shown in live mode I suppose they are correctly formatted, I can paste example of what I send to the ui if it can help.

**Comment by bergie** [comment]
We now generate consistent IDs internally in the packet inspector, so this should no longer be a problem.
