### ISSUE TITLE
Component creation on example projects [usability]

### ISSUE THREAD

**Issue by ClashTheBunny** [noflo/noflo-ui#475]
I couldn't find a way to create components when I opened one of the examples.  I gave up like 5 times after getting nowhere.  I finally read the source and saw that the create component was where I was looking for it, but it wasn't showing up.  I figured out that it is only there on a personal project.  Some sort of grayed out button saying "Create Component" not available in an example would have helped me greatly.

**Comment by jonnor** [comment]
Yes, creating components only available in "project mode". What is really needed is a way to go from example to your own project: #272

**Comment by jonnor** [comment]
Same issue happens with trying to make subgraphs, as I found out during a conference presentation...

**Comment by bergie** [comment]
What we really should do, is make example projects treated as a regular project. That way gists could also ship custom components, multiple graphs, etc.

**Comment by bergie** [comment]
Fixed via the [Edit as Project feature](http://bergie.iki.fi/blog/edit-as-project/) in #703
