### ISSUE TITLE
CodeMirror is only half the vertical screen on master

### ISSUE THREAD

**Issue by ClashTheBunny** [noflo/noflo-ui#477]
I'm trying to edit a component, and it is cutting off the code mirror editor:
![screen shot 2015-05-08 at 11 21 48 am](https://cloud.githubusercontent.com/assets/248361/7532920/16dab6fc-f575-11e4-8b5b-7a343d9d21b6.png)
This does not occur on app.flowhub.io:
![screen shot 2015-05-08 at 11 23 03 am](https://cloud.githubusercontent.com/assets/248361/7532927/2601ccce-f575-11e4-86e1-75a86772af40.png)

This is no error on the console that I can see.  I'm in chrome stable on os x.

**Comment by bergie** [comment]
Interesting. We *do* call `setSize` whenever we get a new component into the editor:
https://github.com/noflo/noflo-ui/blob/master/elements/noflo-component-editor.html#L194

however, this may be an artifact of the point that currently there may be no spec loaded into the editor. I'll investigate:
https://github.com/noflo/noflo-ui/blob/master/elements/noflo-component-editor.html#L273

**Comment by ClashTheBunny** [comment]
Thanks so much!  Worked perfectly!

Randall Mason
clashthebunny@gmail.com
