### ISSUE TITLE
Flowhub v0.8.4 having issues with input on sendNumber

### ISSUE THREAD

**Issue by ClashTheBunny** [noflo/noflo-ui#478]
I'm having some trouble with flowhub's math/sendNumber component sending a string of the number that is input into the "number" input.  I finally got it into a state where it would save the commit to github.  Here is the commit that Flowhub committed:
https://github.com/ClashTheBunny/noflo-fibonacci/commit/88294d817ade57d9bc976a2b190ab477b1ebff81#diff-03225901b041d7e2abff741a4df49cdeR133

As you can see on the highlighted line, the data on the number port is "9" instead of 9.  This gives me errors on my graph which is expecting a number.  I tried restricting the input to my component to only numbers, but that's not working either.  What else can I do to try and diagnose why the interface is changing the number to a string?

I was also able to reproduce it on 18cdf56.

**Comment by bergie** [comment]
Doesn't seem to be an issue any longer
