### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by xtrasmal** [noflo/noflo-ui#479]
Hi everybody,

The UI of the beta version doesn't look as sweet as the current layout(in the image below).
Will the design come back when it is out of testing? Or how can I make it look the same again?

![2f23f921a0f433a6e987a86c1f6c4528](https://cloud.githubusercontent.com/assets/1174877/7553586/04f6491e-f701-11e4-8c06-10a4c4398212.png)

There are loads of things that are great about it.

**Comment by forresto** [comment]
There are tradeoffs, but more advantages to zoomable ui and bezier edges. That design won't be coming back in this fork. 

The graph editor repo is the-grid/the-graph, if you would like to make specific suggestions.
