### ISSUE TITLE
Using Noflo-ui libraries

### ISSUE THREAD

**Issue by xtrasmal** [noflo/noflo-ui#480]
Hello,

FBP seems nice, but I actually like the way you connect all the flo-nodes. I works great and it looks good. I was wondering if we could use then separate.

I would like to have nodes that are connected to ports of other nodes...just that. Some eventlisteners on the ports. Then I'd do some ajax calls and let magic happen. I'm not looking for a whole FBP solution that you guys are making. 

Noflo as a javascript library to do just that, would be really amazing.

**Comment by jonnor** [comment]
@xtrasmal NoFlo is just a JS library. Using Flowhub/NoFlo-UI is optional.

[NoFlo](https://github.com/noflo/noflo) ports are EventEmitters, which you can connect to. You can set up connections programatically if you want (or using the textual .FBP DSL) etc.
We often use the programmatic API in tests. Simple example: https://github.com/noflo/noflo-core/blob/master/spec/ReadEnv.coffee
