### ISSUE TITLE
addnode from server to client

### ISSUE THREAD

**Issue by schmurfy** [noflo/noflo-ui#483]
While fiddling around with my project I wanted to see new nodes pop up on connected clients (in my use case the server can create nodes itself) but sending a addnode request to the flowhub client does not seems to do much :(

The documentation says the graph protocol commands can be used in both directions, is it currently supported ? 

PS: It tried with flowhub

**Comment by bergie** [comment]
Thanks for reporting! Closing since there is a longer conversation about this in #443
