### ISSUE TITLE
Can't register noflo-nodejs runtime in noflo-ui 

### ISSUE THREAD

**Issue by afshin2003** [noflo/noflo-ui#489]
Hi Guys,
I bring my nodejs runtime up. The live IDE URL is: 

http://app.flowhub.io/#runtime/endpoint?protocol%3Dwebsocket%26address%3Dws%3A%2F%2F192.168.251.25%3A3569

Instead of the above URL, I submit this URL on my local IDE:

http://192.168.251.25:3005/#runtime/endpoint?protocol%3Dwebsocket%26address%3Dws%3A%2F%2F192.168.251.25%3A3569

The web page shows no runtime ! The log output is as follows. As you can see I used node-static as file server.

Appropriated
Afshin

[root@biz1 noflo-ui]# node ./node_modules/.bin/static -a 0.0.0.0 -p 3005 .
serving "." at http://0.0.0.0:3005
17:35:32 [304]: /
17:35:32 [304]: /bower_components/webcomponentsjs/webcomponents.js
17:35:32 [304]: /bower_components/polymer/polymer.js
17:35:32 [304]: /bower_components/klayjs-noflo/klay-noflo.js
17:35:32 [304]: /bower_components/hammerjs/hammer.js
17:35:32 [304]: /bower_components/react/react-with-addons.js
17:35:32 [304]: /bower_components/ease-djdeath/index.js
17:35:32 [304]: /bower_components/react.animate-djdeath/react.animate.js
17:35:32 [304]: /browser/noflo-noflo-indexeddb/vendor/IndexedDBShim.min.js
17:35:32 [304]: /bower_components/rtc/dist/rtc.js
17:35:32 [304]: /browser/noflo-ui.js
17:35:32 [304]: /bower_components/codemirror/lib/codemirror.js
17:35:32 [304]: /bower_components/codemirror/mode/xml/xml.js
17:35:32 [304]: /bower_components/codemirror/addon/lint/lint.css
17:35:32 [304]: /bower_components/codemirror/mode/javascript/javascript.js
17:35:32 [304]: /bower_components/codemirror/mode/css/css.js
17:35:32 [304]: /bower_components/codemirror/mode/vbscript/vbscript.js
17:35:32 [304]: /bower_components/codemirror/mode/coffeescript/coffeescript.js
17:35:32 [304]: /bower_components/codemirror/mode/clike/clike.js
17:35:32 [304]: /bower_components/codemirror/mode/htmlmixed/htmlmixed.js
17:35:32 [304]: /bower_components/codemirror/mode/smalltalk/smalltalk.js
17:35:32 [304]: /bower_components/codemirror/mode/yaml/yaml.js
17:35:32 [304]: /bower_components/coffee-script/extras/coffee-script.js
17:35:32 [304]: /bower_components/coffeelint/js/coffeelint.js
17:35:32 [304]: /bower_components/jshint/dist/jshint.js
17:35:32 [304]: /bower_components/codemirror/addon/lint/lint.js
17:35:32 [304]: /bower_components/codemirror/addon/lint/javascript-lint.js
17:35:32 [304]: /bower_components/codemirror/addon/lint/coffeescript-lint.js
17:35:32 [304]: /bower_components/codemirror/addon/lint/yaml-lint.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph.js
17:35:32 [304]: /bower_components/the-graph/the-graph/font-awesome-unicode-map.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-app.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-node.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-graph.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-node-menu.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-node-menu-port.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-node-menu-ports.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-port.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-edge.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-iip.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-group.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-tooltip.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-menu.js
17:35:32 [304]: /bower_components/the-graph/the-graph/the-graph-clipboard.js
17:35:32 [304]: /css/noflo-ui.css
17:35:32 [304]: /app/main.js
17:35:32 [304]: /index.js
17:35:33 [304]: /themes/the-graph-dark.css
17:35:33 [304]: /themes/the-graph-light.css
17:35:33 [304]: /bower_components/codemirror/lib/codemirror.css
17:35:33 [304]: /bower_components/codemirror/addon/lint/lint.css
17:35:33 [304]: /bower_components/codemirror/theme/mdn-like.css
17:35:33 [304]: /css/codemirror-noflo.css
17:35:33 [304]: /app/noflo-logo-74.png
17:35:33 [304]: /bower_components/klayjs/klay.js
17:35:33 [304]: /bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0
17:35:37 [200]: /noflo.ico

**Comment by afshin2003** [comment]
Well, I found the documentation of Flowhub's nodejs runtime. I know that I need to login to the application first to be able to register my runtime manually. But the problem is the Login button does no action. Chrome debugger on load shows just an error "No process defined for inbound node RunTests". What else Do I have to do?

**Comment by afshin2003** [comment]
Maybe I was on a wrong way! So I close this issue and open a new clear one :)

**Comment by jonnor** [comment]
Issue was moved to #490

**Comment by jonnor** [comment]
Just as a note, when running locally, the live-URL typically needs to be `http;//localhost:PORT/index.html`

**Comment by afshin2003** [comment]
Thanks for the note!
