### ISSUE TITLE
Uncaught Error: No process defined for inbound node RunTests

### ISSUE THREAD

**Issue by afshin2003** [noflo/noflo-ui#490]
Hi Guys,
A fresh installation of noflo-ui. All guide lines have been done. By loading application the above error appears on Chrome debug console. Seems to prevent application to run correctly !

BEST,
Afshin

**Comment by jonnor** [comment]
This means the RunTests component can for some reason not be loaded. I checked it exists and is declared in component.json... /CC @bergie

**Comment by jonnor** [comment]
Turns out it was my fault :) It was requring `fbp-spec` that failed. Should be fixed now, but you might need to force reinstall of fbp-spec: `rm -rf components/flowbased-fbp-spec`. Then `grunt build` as usual

**Comment by afshin2003** [comment]
Hi Jonnor,
It seems you've forgotten to push your modifications!

**Comment by jonnor** [comment]
No, its another issue with the same symptoms. Fixing now.

**Comment by jonnor** [comment]
@afshin2003 should be fixed. You may need to `rm -rfcomponents/jonnor-jsonpath` before `grunt build`. Working on adding tests to fbp-spec for browser now..

**Comment by afshin2003** [comment]
You made it, many thanks!
