### ISSUE TITLE
Offline mode (no flowhub required)

### ISSUE THREAD

**Issue by chadrik** [noflo/noflo-ui#491]
Currently noflo-ui queries flowhub to get a list of registered runtime URIs. 
My use case requires running noflo-ui behind a firewall.  It would be great if there was an environment variable that indicated to noflo-ui to read this directly from a json file. e.g. 

```
export NOFLO_UI_REGISTRY_JSON=/path/to/registry.json
./node_modules/.bin/simple-server . 3005
```

An alternate solution would be to implement a flowhub-compatible rest API, but it seems like overkill.  Then again, I haven't dug through the relevant code yet, so maybe changing to a config file would be too invasive of a change.  What do you all think?  In what other ways is noflo-ui specifically tied to flowhub?

**Comment by jonnor** [comment]
@chadrik Just register your runtime(s) manually. On main page, `Register -> Add manually`. It will then be stored in LocalStorage in browser.

**Comment by jonnor** [comment]
This also works in the Chrome app, which is fully offline capable. No need to build manually.
https://chrome.google.com/webstore/detail/flowhub/aacpjichompfhafnciggfpfdpfododlk?hl=en

**Comment by jonnor** [comment]
Related, we'd like to move the runtime discovery out of noflo-ui. That could make alternative schemes easier, #377

**Comment by chadrik** [comment]
I don't want users to have to register the runtime every time they open their browser.

Our use case is that we have dozens of users behind a firewall, and we want to provide them with a single runtime working out of the box.

#377 seems interesting.  It'd be great to hear more concrete ideas on how that would work.

**Comment by bergie** [comment]
For implementing a Flowhub-compatible registry service, the REST API is reasonably simple. And then you can replace the service URL with a local one by setting `NOFLO_REGISTRY_SERVICE` env var to the desired value before building noflo-ui.

**Comment by bergie** [comment]
However, I would like to move bunch of runtime-related stuff to a JSON/YAML file used at build time. Now we have runtime types defined all over the place, as well as hardcoded setup for the browser iframe runtime.

If we implement that, adding other "local" runtimes would be as simple as editing the config file and making a build.

**Comment by chadrik** [comment]
> If we implement that, adding other "local" runtimes would be as simple as editing the config file and making a build.

yes, please!

Is this something you see happening soon?

**Comment by jonnor** [comment]
Moving that to a config is mostly in order to add new runtime *type*, not individual runtimes (instances).

For having a setup on your intranet with a set of runtimes available for everyone, I would recommend running your own registry. There is example code here: https://github.com/the-grid/flowhub-runtime-registry-example
It was created for a client with very similar needs to yours.

We have a task to make the runtime registry URL an app setting instead of a build parameter: #463 (so one does not need to make a custom build)
