### ISSUE TITLE
Runtime connection errors on opening component, secret is reset to null

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#493]
I add a runtime manually. Have tested both specifying a secret and not specifying anything. I go into a graph (in my case in the noflo-hackrf project), select my runtime. Things appear to be connected. In the dev console I see that I get components etc.

I then open a component with tests. The runtime disconnects, console says `WebSocket is already in CLOSING or CLOSED state`.

I try to reconnect the runtime by hitting the reconnect button. Seem to become connected.
However, making a change to a test, nothing happens. Now in the console I see permission errors: 
`Error: start not permitted`.
I inspect the WebSocket data, and see that every message has `secret: null`. Which cannot work, if secret is specified it will be attempted verified, and null is always wrong.

In another instance, I observer that the address of the runtime changed when I went into a component(!).

I have cleared IndexDB for runtimes. Same issue before and after.

**Comment by jonnor** [comment]
Stacktrace of the WS exception

```WebSocket is already in CLOSING or CLOSED state.WebSocketRuntime.send @ noflo-ui.js:47289BaseRuntime.sendNetwork @ noflo-ui.js:46980exports.getComponent.c.setRuntimeDebug @ noflo-ui.js:73161exports.getComponent.c.removeListener @ noflo-ui.js:73199(anonymous function) @ noflo-ui.js:73153exports.WirePattern.inPort.process.task @ noflo-ui.js:7389exports.WirePattern.resumeTaskQ @ noflo-ui.js:7019exports.WirePattern.inPort.process @ noflo-ui.js:7394InPort.handleSocketEvent @ noflo-ui.js:3659(anonymous function) @ noflo-ui.js:3620```

**Comment by jonnor** [comment]
Possibly related to #494

**Comment by bergie** [comment]
Should be no longer an issue
