### ISSUE TITLE
Opening a runtime without a secret fails with TypeError in CollectRemoteNodes

### ISSUE THREAD

**Issue by ComFreek** [noflo/noflo-ui#494]
Steps to reproduce:
1. Set up a new noflo-ui clone (`npm install`, `grunt build`, `simple-server .`)
2. Set up a new noflo-nodejs runtime clone (`npm init`, `npm install noflo --save`, `npm install noflo-nodejs --save`, `npm install noflo-core --save`)
3. Generate a _flowhub.json_ **without** a secret:
   `node_modules/.bin/noflo-nodejs-init --user *** --host localhost --port 3569 --label rt-without-secret`
4. Run `node_modules/.bin/noflo-nodejs`
5. Click on the newly created runtime on noflo-ui's website.

The error message which appears in devtools:

> Uncaught TypeError: Cannot read property 'remote' of nullc.inPorts.add.process @ noflo-ui.js:72688InPort.handleSocketEvent @ noflo-ui.js:3659(anonymous function) @ noflo-ui.js:3620Emitter.emit @ noflo-ui.js:336InternalSocket.regularEmitEvent @ noflo-ui.js:3274InternalSocket.send @ noflo-ui.js:3327(anonymous function) @ noflo-ui.js:3795on @ noflo-ui.js:268Emitter.emit @ noflo-ui.js:336InternalSocket.regularEmitEvent @ noflo-ui.js:3274InternalSocket.connect @ noflo-ui.js:3305(anonymous function) @ noflo-ui.js:3797OutPort.send @ noflo-ui.js:3787(anonymous function) @ noflo-ui.js:72992task @ noflo-ui.js:7389resumeTaskQ @ noflo-ui.js:7019inPort.process @ noflo-ui.js:7394InPort.handleSocketEvent @ noflo-ui.js:3659(anonymous function) @ noflo-ui.js:3620Emitter.emit @ noflo-ui.js:336InternalSocket.regularEmitEvent @ noflo-ui.js:3274InternalSocket.send @ noflo-ui.js:3327(anonymous function) @ noflo-ui.js:3792OutPort.send @ noflo-ui.js:3787(anonymous function) @ noflo-ui.js:18288Emitter.emit @ noflo-ui.js:336InPort.handleSocketEvent @ noflo-ui.js:3665(anonymous function) @ noflo-ui.js:3620Emitter.emit @ noflo-ui.js:336InternalSocket.regularEmitEvent @ noflo-ui.js:3274InternalSocket.send @ noflo-ui.js:3327(anonymous function) @ noflo-ui.js:3795on @ noflo-ui.js:268Emitter.emit @ noflo-ui.js:336InternalSocket.regularEmitEvent @ noflo-ui.js:3274InternalSocket.connect @ noflo-ui.js:3305(anonymous function) @ noflo-ui.js:3797OutPort.send @ noflo-ui.js:3787(anonymous function) @ noflo-ui.js:72654task @ noflo-ui.js:7389resumeTaskQ @ noflo-ui.js:7019inPort.process @ noflo-ui.js:7394InPort.handleSocketEvent @ noflo-ui.js:3659(anonymous function) @ noflo-ui.js:3620Emitter.emit @ noflo-ui.js:336InternalSocket.regularEmitEvent @ noflo-ui.js:3274InternalSocket.send @ noflo-ui.js:3327(anonymous function) @ noflo-ui.js:3792OutPort.send @ noflo-ui.js:3787(anonymous function) @ noflo-ui.js:47929on @ noflo-ui.js:21962Emitter.emit @ noflo-ui.js:22030BaseRuntime.recvRuntime @ noflo-ui.js:46902WebSocketRuntime.handleMessage @ noflo-ui.js:47318(anonymous function) @ noflo-ui.js:47171

The original Coffee script file: https://github.com/noflo/noflo-ui/blob/master/components/CollectRemoteNodes.coffee#L20

In addition, a red banner appears on the website saying "Runtime [runtime id] cannot get sources".

**Comment by bergie** [comment]
We're now handling permissions better, so should be fine
