### ISSUE TITLE
require() problems when embedding noflo-ui in Electron

### ISSUE THREAD

**Issue by ComFreek** [noflo/noflo-ui#495]
### Error description

I am currently trying to serve noflo-ui inside an [Electron](http://electron.atom.io/) instance. However, I face multiple problems.

The first error I got upon loading noflo-ui's index.html (same for dev.html) is as follows:

`Uncaught Error: Failed to require "./nodejs/ComponentLoader" from "noflo-noflo/src/lib/Network.js"`.

The adjacent code block looks:

``` javascript
if (!require('./Platform').isBrowser()) {
  componentLoader = require("./nodejs/ComponentLoader");
} else {
  componentLoader = require('./ComponentLoader');
}
```

Because Electron doesn't support Node.js requires() on the website anyway (AFAIK), I patched Platform#isBrowser (https://github.com/noflo/noflo/blob/master/src/lib/Platform.coffee) to always return true.

Now noflo-ui fails to require `uuid`:

> Uncaught Error: Failed to require "uuid" from "noflo-noflo-runtime-webrtc/runtime/network.js"

The triggering line is https://github.com/noflo/noflo-runtime-webrtc/blob/master/runtime/network.coffee#L8
### Steps to reproduce:
1. Clone noflo-ui, run `npm install` and `grunt build`.
2. Run `npm install electron-prebuilt`
3. Copy the following `main.js` file:
   
   ``` javascript
   var app = require('app');   // Module to control application life.
   var BrowserWindow = require('browser-window');  // Module to create native browser window.
   
   // Report crashes to our server.
   require('crash-reporter').start();
   
   // Keep a global reference of the window object, if you don't, the window will
   // be closed automatically when the JavaScript object is GCed.
   var mainWindow = null;
   
   // Quit when all windows are closed.
   app.on('window-all-closed', function() {
   // On OS X it is common for applications and their menu bar
   // to stay active until the user quits explicitly with Cmd + Q
   if (process.platform != 'darwin') {
       app.quit();
   }
   });
   
   // This method will be called when Electron has finished
   // initialization and is ready to create browser windows.
   app.on('ready', function() {
   // Create the browser window.
   mainWindow = new BrowserWindow({width: 800, height: 600});
   
   // and load the index.html of the app.
   mainWindow.loadUrl('http://localhost:3000/dev.html');
   
     // Open the devtools.
     mainWindow.openDevTools();
   
     // Emitted when the window is closed.
     mainWindow.on('closed', function() {
         // Dereference the window object, usually you would store windows
         // in an array if your app supports multi windows, this is the time
         // when you should delete the corresponding element.
         mainWindow = null;
     });
   });
   ```
4. Run `"node_modules/.bin/electron" .`.

Using the debugger I determined that the following gets never executed:
`require.register("gjohnson-uuid/index.js", function(exports, require, module){`

Thanks for any help on this issue :smile:

**Comment by bergie** [comment]
We're now using webpack, so this is likely to be fixed. Please reopen if needed.
