### ISSUE TITLE
Graph schema

### ISSUE THREAD

**Issue by afshin2003** [noflo/noflo-ui#508]
Hi Guys,
It seems that your current graph schema which you use here is newer than the one you have in noflo library. Would you update that schema or giving the current one here?

Best Regards,
Afshin

**Comment by jonnor** [comment]
Hi @afshin2003. Which schemas are you referring to (here and in which noflo library)?

**Comment by afshin2003** [comment]
Hi,
This one:

https://github.com/noflo/noflo/blob/master/graph-schema.json

**Comment by afshin2003** [comment]
"Here" I mean the schema by which you produce the json file.

**Comment by jonnor** [comment]
That schema looks roughly correcct. What differences are you seeing?

**Comment by afshin2003** [comment]
noflo-ui sets some metadata for components coordination (i.e. x, y, width, height, label) and additional properties in such as 'project', 'id'...

Actually I am using a json editor which can be used for minor modifications on the graphs. It does it by using the provided json schema :)

**Comment by forresto** [comment]
width, height is a the-graph bug... it should not be mutating the graph :(

**Comment by jonnor** [comment]
Those are all found in `.properties` or `.metadata` of group/component, right? These have `additionalProperties: true`, so the schema is technically correct?

**Comment by afshin2003** [comment]
You mean my json editor should be able to handle them! Ok, I thought maybe it's better to feed it with the exact schema .

**Comment by jonnor** [comment]
The schema for graphs has now been moved to `fbp`, and brought up to date. https://github.com/flowbased/fbp
