### ISSUE TITLE
Not possible to inspect data going out on exported port

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#520]
Happens both for inports and outports. Makes debugging for some projects really hard, cause cannot see the relevant data... Especially when one cannot go up to outside level, like in case of a graph mounted by MsgFlo etc.

Current workaround: Use a `core/Repeat` or similar around every exported in/outport...

Needs fix in the-graph, probably: https://github.com/the-grid/the-graph/issues/229

**Comment by bergie** [comment]
With 0.29.0 it is, assuming
