### ISSUE TITLE
Show project CI/test status

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#526]
Useful to have an overview over whether changes that were pushed passed in CI (and not just locally).

Should probably default to the tracking branch of the branch one is currently on, but at least also allow to show latest `master` and recent tags. Optionally also allow to browser other builds/versions.

Probably best done using the Github API, as we already have API key, and most CI service providers (like Travis CI) report their status there.

**Comment by bergie** [comment]
Out of scope
