### ISSUE TITLE
Switch to Polymer 1.0+

### ISSUE THREAD

**Issue by jogibear9988** [noflo/noflo-ui#537]

**Comment by bergie** [comment]
Depends on the-grid/the-graph#222

**Comment by forresto** [comment]
@bergie we have a circular dependency here then. Not really, we just have to bite the bullet at the same time.

**Comment by jonnor** [comment]
Proposed way forward is to:

* Make the-graph be React-only, moving the Polymer components/wrappers into noflo-ui
* Once all the Polymer using code is in noflo-ui, do a sweep of upgrading from version 0.5 to 1.0

Longer term we're probably getting rid of Polymer completely, but this we will do component/widget by widget as they get other improvements - not rewriting for the sake of rewriting. Also keeping thin Polymer wrappers, and then at some point when the innards are all Polymer free we can drop Polymer in one go.

**Comment by jonnor** [comment]
Old version of Polymer is last sticking point in our VersionEye checks as well:
`Dependencies with unknown licenses: 1`
https://www.versioneye.com/pullrequests/57e13210c2cd3f0018cff57c

**Comment by bergie** [comment]
Migration guide: https://www.polymer-project.org/1.0/docs/migration

**Comment by bergie** [comment]
Polymer 2.x is now in preview as well: https://www.polymer-project.org/2.0/docs/about_20

Unfortunately it seems that Polymer's NPM packaging is somewhat lacking... Polymer/polymer#326

However, we have noflo-polymer working with Polymer 1.x from NPM now, so that is a start noflo/noflo-polymer#16

**Comment by jonnor** [comment]
Polymer 2.x says explicitly to not use it for production, so don't see a reason to jump onto that at this time.

**Comment by jonnor** [comment]
(and the wuppmigration path

**Comment by jonnor** [comment]
Some migration notes from the-graph experience at https://github.com/kristianmandrup/the-graph/blob/polymer2/Polymer2-migration-notes.md
