### ISSUE TITLE
No error message on failing to connect to non-SSL runtime from https://flowhub.io

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#543]
Should suggest to use http://flowhub.io instead, until we can go SSL-by-default

Causes confusion like in https://github.com/noflo/noflo-ui/issues/433
Can happen with all WS runtimes. Perhaps most prominently noflo-nodejs, which currently has no SSL support: https://github.com/noflo/noflo-nodejs/issues/54

**Comment by forresto** [comment]
Also the browser examples, which load iframe from http.

**Comment by jonnor** [comment]
Was going to say we can just switch the browser runtimes to HTTPS, but it turns out that noflojs.org SSL is broken: https://github.com/noflo/noflo.github.io/issues/61

**Comment by bergie** [comment]
For reference, here is the original Chrome bug for blocking `ws` on `https`

https://bugs.chromium.org/p/chromium/issues/detail?id=85271

**Comment by bergie** [comment]
Note: this also affects the Chrome app:

> Refused to frame 'https://noflojs.org/noflo-browser/everything.html?fbp_noload=true&fbp_protocol=iframe' because it violates the following Content Security Policy directive: "frame-src 'self' blob: filesystem: data: chrome-extension-resource:".

Refs #673

**Comment by bergie** [comment]
Now we have a nice error message:

![screenshot 2017-11-17 at 20 17 08](https://user-images.githubusercontent.com/3346/32964726-69330534-cbd4-11e7-8cac-6e501b7c29d6.png)
