### ISSUE TITLE
Connecting to an actively running runtime

### ISSUE THREAD

**Issue by chadrik** [noflo/noflo-ui#555]
I've got my runtime hooked up to noflo-ui but I'm having trouble viewing a running graph once I exit the `#project` page. 

Here are the steps I'm taking:

- create a new project. associate it with my runtime.  create a graph that will run for a long time.  press 'play' to start the graph.  exit back to the main page.
- check my terminal to confirm the runtime is still actively running.
- from the main page, click on my runtime (under "Runtimes") to visit http://localhost:8000/#runtime/575ed4de-39c9-3698-a4be-f5395d9eda2f
- noflo-ui then issues the following commands:

```python
{
 'command': 'getruntime',
 'payload': {'secret': '9129923'},
 'protocol': 'runtime'
}
{
 'command': 'list',
 'payload': {'secret': '9129923'},
 'protocol': 'component'
}
{
 'command': 'getstatus',
 'payload': {'graph': '575ed4de-39c9-3698-a4be-f5395d9eda2f',
             'secret': '9129923'},
 'protocol': 'network'
}
```

The runtime responds to the first two commands appropriately, but the last one is confusing.  `575ed4de-39c9-3698-a4be-f5395d9eda2f` is my runtime id.  There is no such graph, so my runtime responds that it is neither started nor active. The end result is that there is no graph displayed on the page.

My expectation was that the client would issue a query to the runtime like "give me the list of actively running graphs" so that it could present the user with a list of choices.  After choosing, the client would then follow up with a query like "for graph X, give me the components and their connections" so that it can rebuild the graph on its side.  Is there something that I'm doing wrong or is this not supported? 

Thanks in advance.

**Comment by jonnor** [comment]
Yes this is how it should have worked, but it currently does not.
The problem is that 'project mode' assumed the runtime is an empty vessel, overiding all the state. On conversely live mode has No connection to projects at all so one cannot make changed in a project that way.

**Comment by chadrik** [comment]
ok, I understand the relationship between these two views a bit better, but I'm still having a problem with basic usage.

If I author the graph directly in Live mode, then exit the view, and then re-enter it, the page does not display the running graph (i.e. components and edges).

In this scenario, when the client issues the `getstatus` command with `'graph': '575ed4de-39c9-3698-a4be-f5395d9eda2f'` my runtime correctly responds with `'running': True, 'started': True`.  It seems to me that if the client knows that the graph is started and running, but knows nothing about what the graph actually looks like, it ought to follow up with a query to get the graph from the runtime.  I tried sending an `addnode` command to the client, but it did not have any affect.  

How can I tell the client to update the graph on its side?

**Comment by jonnor** [comment]
For getting the state of runtime in "live mode", see #390 and the commits linked to that for workaround.

**Comment by chadrik** [comment]
That helps clarify things a little more, but it's unclear to me how to get noflo-ui to issue the `getsource` command when I start live mode.  My runtime supports the 'component:getsource' capability. 

Just to be sure, I used the endpoint referenced by your commit for my runtime:  http://localhost:8000/#runtime/endpoint?protocol%3Dwebsocket%26address%3Dws%3A%2F%2Flocalhost%3A3569

It worked, but it just changed the graph id to 'ws%3A%2F%2Flocalhost%3A3569'.  No 'getsource' command was issued.

I'm thinking I must be making a workflow mistake.

**Comment by chadrik** [comment]
By the way, if you're interested in experimenting with my runtime, it's here:  https://github.com/chadrik/rill

**Comment by jonnor** [comment]
@chadrik the runtime must have a `graph` property in the `runtime` message (currentl main graph), then it will send `getsource` for that

**Comment by chadrik** [comment]
closing this as a duplicate of #390
