### ISSUE TITLE
Runtime/test status not showing when opening component editor from sidebar

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#561]
Top left corner, where it usually says 'connected' etc is just blank.
When going to edit a graph it shows up again.

Tested on git master, on commit 87d150e3b5e

**Comment by jonnor** [comment]
Still happens in 0.15.0

**Comment by bergie** [comment]
It _does_ show when opening a component from a graph:

![screenshot 2017-02-17 at 19 33 06](https://cloud.githubusercontent.com/assets/3346/23078214/01638914-f548-11e6-973e-be886c0a382e.png)

**Comment by jonnor** [comment]
So how is that different from opening a component using the sidebar?
