### ISSUE TITLE
Specify versioned dependencies

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#567]
Backwards-incompatible changes are being planned as part of NoFlo 1.0.
noflo-ui uses a bunch of NoFlo libraries, and right now these are specified with `*` meaning latest/master.
This will break things when backwards-incompatible 1.x.x versions land. So we need to lock down dependencies (which is generally a good idea) before that.

However, a large number (almost all) of the dependencies are lacking proper releases. So that is needed firstmost:

* [x] https://github.com/noflo/noflo-github also does not have up to date release
* [x] https://github.com/noflo/noflo-indexeddb missing releases
* [x] https://github.com/noflo/noflo-polymer zero releases
* [x] https://github.com/noflo/noflo-core is 1 year old 
* [x] https://github.com/noflo/noflo-dom 0 releases
* [x] https://github.com/noflo/noflo-routers last (first) release is 2 years old
* [x] https://github.com/noflo/noflo-groups last (first) release is 1.5 years old
  * noflo-core
* [x] https://github.com/noflo/noflo-objects has 0 releases
* [x] https://github.com/noflo/noflo-interaction 0 releases
* [x] https://github.com/noflo/noflo-localstorage 0 releases
* [x] https://github.com/noflo/noflo-ajax last release 1 year old
* [x] https://github.com/noflo/noflo-strings last release 0.5 years old

**Comment by jonnor** [comment]
Each of these libraries might reference other libraries, and should be checked recursively.

**Comment by jonnor** [comment]
Actually it looks like only noflo-groups has a dependency on other NoFlo libraries. So that should make the process fairly straightforward.

**Comment by jonnor** [comment]
Note that the libraries themselves probably should not specify `noflo` version. This way it is the consuming app which decides this.

An open question is which noflo version noflo-ui should use though? Latest 0.5.x, 0.6.x or 0.7.x ?

**Comment by bergie** [comment]
I think we should go for NoFlo 0.7.x

**Comment by bergie** [comment]
While I'm at it, I'll also make sure these are available via NPM for eventual switch to WebPack builds
