### ISSUE TITLE
Can't get app.flowhub.io to work: No components show up in the search box

### ISSUE THREAD

**Issue by sejnub** [noflo/noflo-ui#610]
My problem is that no components show up in the search box of app.flowhub.io

I tried two ways to get a list of components into the search box but both failed.

**A)** Standard components do not show up like they should if the example under https://docs.flowhub.io/article/70-getting-started-browser is correct

- I follow the steps of "Getting Started (Browser)"
- Under "Search and add components" Step 2. It says that I get a list of components 

_But there are no components_. I could understand if the behaviour is correct an there are no standard components in a new project but then the "Getting Started" text is incorrect.

**B)** If I create a new component in the code editor it doesn't show up in the Search box

- I create a new browser project like described under https://docs.flowhub.io/article/70-getting-started-browser.
- I create a new component by clicking "component create" in the left drawer 
- I modify the source code so that no errors or warnings are shown
- I exit the editor by opening the drawer again and clicking on the project (I found no other way to exit the editior)

The drawer shows my new component but _there are no components_ found by the search box.

 
Is there something I totally got wrong? What did I miss?

Remark: When I instead choose one of the examples like "Animated clock" then there are components in the search box.

**Comment by aretecode** [comment]
@sejnub 

**A)** make sure all of the components are valid.

**B)** 
**B-1)** Make sure you've selected the correct runtime.
**B-2)** Close & re-open flowhub.
**B-3)** Try syncing with a github repo and edit the components in your usual editor.

**P.S.** There is a known bug with the search box not finding components, it should be somewhere in the issues.

Hopefully that helps! :-)

**Comment by sejnub** [comment]
@aretecode 

A) The components are valid. Still no components found by the search box.

B-1) Done Still no components found by the search box.
B-2) Done. Still no components found by the search box.
B-3) Haven't managed to do that by now. There is some strange behaviour I don't understand. I am on it. 


But then just one time the search box listed components after logging out and deleting the browser cookies. I still can't reproduce that lucky behaviour.


To get more information about this bug and to learn I built a simple docker image for noflo-ui. You can find it under https://hub.docker.com/r/sejnub/noflo-ui/
**When I run that docker image suddenly the search box finds lots of components** and I can build new ones and add them to the graph. 
**Why does it work with my own server but not (except one time) with app.flowhub.io?**

I really don't want to waste your time so I tried to find the reported issue that @aretecode mentioned to see if it addresses the same problem but I could not find it.

**Comment by jonnor** [comment]
@sejnub are you accessing app.flowhub.io via HTTPS? This cause a problem connecting to runtimes which are not SSL capable, see #433

**Comment by sejnub** [comment]
Great!! Thanks, jonnor! That seems to be the reason. 

An informative error message would have been extremely helpful. Sorry for not having the idea to try plain http.

Issue can be closed.

**Comment by jonnor** [comment]
Good to hear it was a known issue (with workaround). Getting error handling in we can handle in #433
