### ISSUE TITLE
Help with zoom and background

### ISSUE THREAD

**Issue by Steve1820** [noflo/noflo-ui#614]
Hi guys,

I am having issues trying to find the "zoom" section of the code. Anyone can help out?

Also, I can't seem to locate where to change the background is? I can change colours...are we able to upload an image as a background?

Thanks guys and much appreciated!
Steve

**Comment by forresto** [comment]
Zoom happens here: https://github.com/the-grid/the-graph/blob/master/the-graph/the-graph-app.js#L172

**Comment by Steve1820** [comment]
Thanks Forresto!

I was also wondering how to change the right click to a left click and how to make the inports/outports bigger (easier to connect nodes together)?

Again, thank you for your reply!

Steve

**Comment by bergie** [comment]
Related to https://github.com/flowhub/the-graph

Please file there if this is still relevant.
