### ISSUE TITLE
Configure examples to show on build time

### ISSUE THREAD

**Issue by ruippeixotog** [noflo/noflo-ui#617]
Unless I overlook something, there is no way to configure the examples to appear on the noflo-ui home page. They seem to be hardcoded in `noflo-main.html`, with no way to override them. It would be useful to configure them when noflo-ui is built, so that examples can be customized, e.g. for new runtimes or for personal examples.

What would be the best solution for you? There is an `examples.json` file in the project root which doesn't seem to be used anywhere... It would be nice to include it in `noflo-main.html` someway. The easiest way I can think of is to define a `$NOFLO_EXAMPLES_JSON` variable in the Gruntfile loading `examples.json` and using it in `noflo-main.html`, but it seems a bit hackish. What do you think?

**Comment by bergie** [comment]
Yeah, this could use refactoring. Ideally we'd have a YAML/JSON file per known runtime, and derive runtime settings, docs, and examples list based on it

**Comment by jonnor** [comment]
Some initial work on moving to YAML files  in `runtimeinfo` branch.

**Comment by jonnor** [comment]
See #619 for start of moving to declared runtime info.
Could then add a key `examples` to the runtime info YAML, putting the existing examples from noflo-main, and then populate the examples list from this information at runtime.

**Comment by ruippeixotog** [comment]
That's great to know! Is there any way I can contribute?

**Comment by jonnor** [comment]
If you're willing to give it a shot, fork noflo-ui, checkout the `runtimeinfo` branch and make the changes described. Then push to a new branch and make a pull request of it.

**Comment by ruippeixotog** [comment]
Will do that tomorrow!

**Comment by jonnor** [comment]
@ruippeixotog cool! I've pushed the changes to `master` now, so no need to checkout a special branch.
