### ISSUE TITLE
app.flowhub.io is not working

### ISSUE THREAD

**Issue by rebulanyum** [noflo/noflo-ui#623]
Hello.

I was trying to learn noflo within flowhub. Found app.flowhub.io that looks like it's your IDE, hosted on web. That's cool but it's not working right now. 

The point is; I'm followiing [this link](https://docs.flowhub.io/article/70-getting-started-browser), a step by step guide for a creating "hello world" project on flowhub. I just stuck on the 2nd step under the "Search and add components" title: It says 

> Search for "alert," then tap `prompts/Alert` to add that component to your graph

Nope. It's not working. I've looked at console and saw this

![flowjsssss](https://cloud.githubusercontent.com/assets/1245382/19178995/65e6d260-8c61-11e6-9afe-af7cd7cb371e.png)

The flowhub website is https and noflo website is http. While flowhub is trying to load javascript libraries (framework) from noflo website it encounters this error. Well, you can not use http inside https website. Sorry...

I want to ask "Can you please fix this?", but I won't: since I've checked that It is already hosted with https. Please have a look on [this link](https://noflojs.org). Yep, it's interesting that the SSL certificate for the website is created for "*.github.com" and issued by Digicert. You must be rich guys :).

The point is, when I changed the src attribute of iframe seen on the image above from http to https. It's still not working. So can you please have a look on this?

**Comment by rebulanyum** [comment]
Sorry for that. I've just realized now that this topic is already opened with #543 .

**Comment by jonnor** [comment]
Thanks for reporting! Lets track this it in #543. I've posted a link to the noflojs.org SSL issue there.
