### ISSUE TITLE
Use node icons other than Font Awesome

### ISSUE THREAD

**Issue by ruippeixotog** [noflo/noflo-ui#630]
There seems to be no way to set an icon other than the ones included in Font Awesome. It would be nice to allow setting custom text or arbitrary SVG images as background.

An use case for custom text is a component such as a counter or statistic that is continuously updating their icon to show the latest value. With that, the full unicode character set could also be used for extra icons. With arbitrary SVG images, components would also be able to generate SVG icons to provide rich information about a processing operation.

What do you think?

**Comment by bergie** [comment]
This also would need support in https://github.com/flowhub/the-graph

**Comment by bergie** [comment]
Right now https://github.com/flowbased/fbp-protocol specifies that node icons must be from font awesome. 

Please file a feature request there if this is still relevant.

**Comment by ruippeixotog** [comment]
Hi @bergie, thanks for the update! I stopped restricting myself to the fbp-protocol it in my FBP runtime, so I do not need it myself anymore.

Nonetheless, I think that this is still relevant for fbp-protocol. IMO, it's a natural design choice not to depend on the icon names of a specific library in a protocol that doesn't even require a frontend.
