### ISSUE TITLE
Fetching runtime data with existing login fails silently

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#632]
Get `401 Unauthorized` from get runtime request. However this error is never surfaced to the user, but silently ignored. This can cause the runtime list to be outdated, and probably also fails on syncing projects.

Logging out and in a gain fixed the problem. So seems like a token expiration issue.

**Comment by jonnor** [comment]
For token expiry, there is probably also something we should be doing which we are not.

**Comment by trustmaster** [comment]
The latest Passport API provides `refresh_token` upon login that can be used to refresh an `access_token` without forcing the user to relogin.
