### ISSUE TITLE
Deprecate the Chrome app

### ISSUE THREAD

**Issue by bergie** [noflo/noflo-ui#673]
As [announced by Google last August](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html), Chrome apps are being deprecated on most platforms by 2018.

We currently have a version of Flowhub available in the Chrome Web Store. The primary reason for the Chrome app to exist is communications with USB MicroFlo devices.

Apart from the looming deprecation of Chrome apps altogether, the additional downside to having an app is more support burden, as the Chrome-specific functionality is not part of our test suite. Things break easily, like was seen with login recently in #657.

Also, content security policy changes hurt Flowhub. For example, we can't open IFRAME runtimes in the Chrome app now.

Proposed steps for deprecating the Chrome app version of Flowhub:

* [ ] Release a version of the Chrome app that communicates deprecation and provides a [uninstall button](https://developer.chrome.com/extensions/management#method-uninstallSelf). There should be a link to the Flowhub webapp. It should also inform that Flowhub webapp is offline capapable, and that in Chrome one can use the "add to homescreen" feature to make it appear as a native app

Future

* [ ] Create a Chrome extension for MicroFlo that we [can talk with from the web app](https://developer.chrome.com/extensions/messaging#external-webpage)
* [ ] Investigate how much [Web Bluetooth](https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web) and [WebUSB](https://wicg.github.io/webusb/) could be used to talk with MicroFlo directly from the browser

More details in the [Chrome app to web migration guide](https://developers.chrome.com/apps/migration)

**Comment by bergie** [comment]
On a quick read of [Chrome extension message passing docs](https://developer.chrome.com/extensions/messaging), it seems we could do this in the following way:

Make EnsureLocalRuntimes do a one-time request to the MicroFlo extension

```coffeescript
chrome.runtime.sendMessage microfloExtensionId,
  command: 'list_runtimes'
, (res) ->
  # Add runtimes returned by extension to the list
```

Then fbp-protocol-client could include code for [creating a runtime connection](https://developer.chrome.com/extensions/runtime#method-connect) with the extension and passing messages with it. This would be roughly similar to the existing iframe client.

**Comment by jonnor** [comment]
USB devices can come and go an any time. So extension should be able to update available runtimes at the appropiate times?

**Comment by bergie** [comment]
@jonnor good point. So then we should have a persistent channel so extension can send "new runtime" and "removed runtime" messages at any point

**Comment by jonnor** [comment]
Somewhat releated to #377

**Comment by jonnor** [comment]
Since MicroFlo is currently a bit broken in Flowhub, and more work (outside of Flowhub) is needed to make it work proper - we'll deprecate the app sooner rather than later, and re-introduce this functionality later. I've updated the issue description to reflect this.

**Comment by jonnor** [comment]
Also probably the Chrome extension would be a general "runtime communication" extension. That way we can use it not just for MicroFlo, but also MsgFlo/NoFlo and so on, using discovery methods which are not available in a browser directly, like mDNS

**Comment by bergie** [comment]
Ok, Chrome Apps are gone now, so we can close this

https://arstechnica.com/gadgets/2017/12/google-shuts-down-the-apps-section-of-the-chrome-web-store/
