### ISSUE TITLE
Noflo UI does not seem to be working on an iPad air 2, hangs while loading

### ISSUE THREAD

**Issue by geertbongers** [noflo/noflo-ui#694]
The message "Preparing flowhub" keeps blinking but nothing is happening. I also tried the hosted version 0.17.0, but same result.

**Comment by bergie** [comment]
This is an issue with the Polymer version we're using coupled with the partial state of web components support in latest mobile Safari.

Will be either fixed with #537 or with more comprehensive web components support in the iOS version of Safari, which ever happens first

**Comment by geertbongers** [comment]
Thanks for the quick reply. Is there a version that was working on mobile Safari?

**Comment by bergie** [comment]
This was broken by a Safari update, not by us, so unfortunately not at the moment

**Comment by bergie** [comment]
iOS is now fixed in #668, however we need to still fix non-PointerEvent touch handling in flowhub/the-graph#364

![img_0012](https://user-images.githubusercontent.com/3346/29382220-35ab4394-82cc-11e7-879d-ebbece1d8303.jpg)
