### ISSUE TITLE
Graph data sent to runtime multiple times when refreshing browser

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#698]
To reproduce

* Have a project open in Flowhub, with a runtime connected
* Refresh the page (using Ctrl+F5 or similar)
* Observe communication going to runtime on WebSocket. Either on runtime side or using Chrome devtools

Expected:
`graph:clear`, `graph:addnode` and similar commands are sent *once*

Actual:
`graph:clear`, `graph:addnode`, ... is sent *three* times

**Comment by jonnor** [comment]
In MsgFlo one ends up with 3x the number of participants running due to the duplicated `addnode` commands. Possibly other runtimes have similar issues, for instance IIPs might get sent multiple times

**Comment by bergie** [comment]
One of the three was eliminated with noflo/noflo-runtime#116
