### ISSUE TITLE
Register runtime from live mode

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#708]
This way it will be available in the future under `Runtimes`, including on other devices user may have.
In the new runtime discovery/registration flow, the runtime itself also does not register, so in order for pinging to actually work, the UI must do it.

Should be triggered opening the live mode (looking at the runtime read-only), or when hitting 'edit as project'.

**Comment by bergie** [comment]
Some code in https://github.com/noflo/noflo-ui/pull/680/commits/5a2c57a1e97ff903bbb784ba7d87ec3cb56acb48
