### ISSUE TITLE
[Feature-request] noflo-ui as Firefox addon

### ISSUE THREAD

**Issue by jibe-b** [noflo/noflo-ui#715]
As noflo-ui is already available as a Chrome extension, there should be little work to make it also available as a Firefox addon.

Guides are available at: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by bergie** [comment]
Actually, there is little benefit in doing an extension instead of just using Flowhub/noflo-ui is a offline-capable web app. We're intending to sunset the Chrome app soon #673

**Comment by jibe-b** [comment]
I need to try it offline then.
