### ISSUE TITLE
Unable to Add Inventory Items

### ISSUE THREAD

**Issue by LightshadeSheridan** [noflo/noflo-ui#780]
For the past three or four days we have not been able to add any inventory items into our FlowHub. When "Save & Close" or "Save & Add Another" is selected, the new item is moved into the "Inventory To Be Added" section. No matter how long we wait, (we have tried waiting hours), the item doesn't get put into our inventory and instead sits in the "Inventory To Be Added" section until we give up and hit "Cancel". We called the other day and were told that this was probably an issue with our internet connection, but we have no trouble streaming videos and music or downloading large files quickly. I uploaded a video to demonstrate what happens. https://www.youtube.com/watch?v=0a4wzPbUrnw&feature=youtu.be

**Comment by bergie** [comment]
I think you're talking about some other Flowhub than this one (http://flowhub.io/ide/)
