### ISSUE TITLE
GitHub tab is not functional, even after logging in and granting permissions

### ISSUE THREAD

**Issue by bodom0015** [noflo/noflo-ui#784]
Good afternoon! I am trying to create a simple example component by following the documentation here: https://docs.flowhub.io/github-integration/

Unfortunately it seems like these steps no longer reflect the newest version of the view(s), and as a result I can't seem to find much of the functionality described by these steps. I have attempted this example component in two places with the same results: both on the [FlowHub](https://app.flowhub.io), as well as from a locally running NoFlo UI v0.22.0 in a [Docker container](https://github.com/cropsinsilico/noflo-ui/blob/master/Dockerfile).

In both cases, after logging in and authorizing FlowHub to see my public repositories, I am still unable to click on the GitHub tab to view my repositories and import my test project.

Am I configuring something wrong here? Or is this functionality possibly missing?

**Comment by bergie** [comment]
Verified, appears to be a regression in 0.22. Will try to fix later today

**Comment by bodom0015** [comment]
Thank you so much for the quick response! 👍 
I have rebuilt and it is now working!

As a side note: would you be interested in my Dockerfile, with a small addition to the README on how to use it? I'd be more than happy to make a PR, if it might be helpful to someone else

**Comment by bergie** [comment]
@bodom0015 yes, that'd be great!

**Comment by bodom0015** [comment]
@bergie Fantastic! I've created a PR as issue #787 :)

**Comment by bergie** [comment]
@bodom0015 thanks! I'll look at it tomorrow.
