### ISSUE TITLE
Getting "Module build failed: Error: Cannot find module 'coffeescript'" on a fresh checkout

### ISSUE THREAD

**Issue by SillyFreak** [noflo/noflo-ui#804]
On a fresh checkout on the master branch, and after

    npm install
    npm run build

I get the error from the title:

    Module build failed: Error: Cannot find module 'coffeescript'

The following worked for me:

    npm install 'coffeescript@<2'

I think that should be in the dependencies, but as the build on Travis works, it may be more intricate.

    $ node --version && npm --version && git branch -v
    v8.5.0
    5.5.1
    * master 61fbd98 Merge pull request #791 from noflo/greenkeeper/fbp-1.6.0

**Comment by bergie** [comment]
I think this is a side effect of the NoFlo 1.0 release cycle. Will update this repo accordingly today
