### ISSUE TITLE
app.flowhub.io links - HTTP/S confusion

### ISSUE THREAD

**Issue by bodom0015** [noflo/noflo-ui#848]
I wasn't sure where to file this as it isn't so much an issue with noflo-ui, but the flowhub.io service itself (for which I could not find a standalone git repo).

There appear to be two different contexts for app.flowhub.io: https://app.flowhub.io and http://app.flowhub.io. In the READMEs for both [the-graph](https://github.com/flowhub/the-graph) and [noflo-ui](https://github.com/noflo/noflo-ui), the links switch between the HTTP and HTTPS versions.

Steps to Reproduce:
1. Navigate to https://app.flowhub.io
2. Login via GitHub (you will be asked to authorize flowhub as an GitHub application)
3. Create a new project or register a new runtime
4. Navigate to http://app.flowhub.io (notice, you are no longer logged in)
5. Login via GitHub (you will be again asked to authorize flowhub as an GitHub application)

Expected Results:
* The new project/runtime created under step 3 should still be present after step 5

Actual Results:
* Switching from HTTPS to HTTP does not show all of the user's projects / runtimes that were created under the HTTPS version
* This can be very confusing

Possible Mitigation Steps:
* http://app.flowhub.io (port 80) could redirect to https://app.flowhub.io (port 443) to prevent this problem

**Comment by bergie** [comment]
Yes, we'd eventually want to go HTTPS-only and redirect, especially with the upcoming [insecure warnings for HTTP](https://venturebeat.com/2018/02/08/chrome-will-start-marking-all-http-sites-as-not-secure-in-july/).

However, the reason we haven't done so yet is that you can't open unencrypted WebSocket connections from a HTTPS page, and by default both NoFlo and MsgFlo runtimes are unencrypted, meaning that you couldn't connect to them from Flowhub. As soon as they support SSL, we can switch over. See #433 for more details.

**Comment by bergie** [comment]
Note: noflo-nodejs version 0.10.0 and above now directs users to `https` if SSL certificate is provided for the runtime.
