### ISSUE TITLE
Noflo Vue.js / ElementUI 

### ISSUE THREAD

**Issue by roscopecoltran** [noflo/noflo-ui#884]
Hi guys,

Hope you are all well !

I was wondering if there is a vue.js version of noflo-ui because I wished to add it as a component in a vue-admin framework.

Refs.
- https://github.com/PanJiaChen/vue-element-admin
   - **demo**: http://panjiachen.github.io/vue-element-admin/#/components/drag-kanban
-  https://github.com/PanJiaChen/vueAdmin-template
   - **demo**: http://panjiachen.github.io/vueAdmin-template

My Goal:
- Create an admin component like https://m-reda.github.io/linker/ and be able to automate some tasks (fbp) in my vue-admin and re-use noflo or msgflow business logic.

If no project is intended in this direction, what would be your advices/safe-guards to make the port easy and stable ?

Have a great day all !

Cheers,
Rosco Pecoltran

**Comment by jonnor** [comment]
To my knowledge no such port exists, and 'porting' the code would be a complete rewrite of the entire application. Not something we will do.

You can integrate it as a Vue component by embedding it in an iframe. It should play quite nicely with that, much info like project/repo to load and runtime to connect to is specifyable in the URL already.

**Comment by bergie** [comment]
The other way of using noflo-ui (or parts of it) in a Vue application should however be possible by utilizing the Web Components noflo-ui provides. We haven't designed it for embeddability, though.
