### ISSUE TITLE
Taking a long time to save the custom components

### ISSUE THREAD

**Issue by pidugusundeep** [noflo/noflo-ui#908]
I am creating my own custom components in flowhub which includes adding various inputs and outputs with some transformations of data for the outputs from the inputs, it takes a lot of time to save it always shows "`loading ...`" for a very long time always even if the code change is just a couple of lines, if I leave it loading and go back to the main graph then I will be still able to add the new component to the new main graph, but when i try to run the graph it shows me 
`**Uncaught Error: Component app/customconponent is not in library**`, i even tried installing the local noflow nojs environement which also didnt help me please let me know if this takes time always or should i be using the existing function components instead of creating the custom components ?

**Comment by bergie** [comment]
Doesn't seem to be an issue any longer
