### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by thxmike** [noflo/noflo-ui#924]
When running npm install on a fresh install, I receive the following error message from npm:

npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for jsonpath@~0.11.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'fbp-spec'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:

I am unable to continue through the installation steps of this product

**Comment by Mungoid** [comment]
This is a bit of a late reply (not sure why nobody has replied to this already), but your issue is likely due to a firewall rule regarding 'git://' urls. If you look at the package.json you will notice it is used for git repos. 

Using ```git config --global url."https://".insteadOf git://``` should fix the issue
