### ISSUE TITLE
security - iframe access to localStorage

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#99]
This graph will pop up your Github key. 

```
loadbang(core/Output) OUT -> IN popup(core/MakeFunction)
'alert(window.localStorage["github-token"]);' -> FUNCTION popup
'bang' -> IN loadbang
```

You would have to run a graph from somebody else for this to be used maliciously, but that might be as easy as clicking a link to a gist-stored graph. I'm not much of a hacker, but it could be worse, messing with indexdb entries, mutating graphs...

So, at least for the hosted version, and graphs loaded from gists, the iframe runner should be on another server. This is how jsfiddle, jsbin, et al do it.

**Comment by jonnor** [comment]
We now serve the browser runtimes from `noflojs.org` (or users domain) never app.flowhub.io - so this issue should be gone, right?
